//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftWA.Usuario {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", ConfigurationName="Usuario.Usuario")]
    public interface Usuario {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://usuario.services.softprog.pucp.edu.pe/Usuario/buscarPorEmailUsuarioRequest" +
            "", ReplyAction="http://usuario.services.softprog.pucp.edu.pe/Usuario/buscarPorEmailUsuarioRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftWA.Usuario.buscarPorEmailUsuarioResponse buscarPorEmailUsuario(SoftWA.Usuario.buscarPorEmailUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usuario.services.softprog.pucp.edu.pe/Usuario/buscarPorEmailUsuarioRequest" +
            "", ReplyAction="http://usuario.services.softprog.pucp.edu.pe/Usuario/buscarPorEmailUsuarioRespons" +
            "e")]
        System.Threading.Tasks.Task<SoftWA.Usuario.buscarPorEmailUsuarioResponse> buscarPorEmailUsuarioAsync(SoftWA.Usuario.buscarPorEmailUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://usuario.services.softprog.pucp.edu.pe/Usuario/listarPorRolUsuarioRequest", ReplyAction="http://usuario.services.softprog.pucp.edu.pe/Usuario/listarPorRolUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftWA.Usuario.listarPorRolUsuarioResponse listarPorRolUsuario(SoftWA.Usuario.listarPorRolUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usuario.services.softprog.pucp.edu.pe/Usuario/listarPorRolUsuarioRequest", ReplyAction="http://usuario.services.softprog.pucp.edu.pe/Usuario/listarPorRolUsuarioResponse")]
        System.Threading.Tasks.Task<SoftWA.Usuario.listarPorRolUsuarioResponse> listarPorRolUsuarioAsync(SoftWA.Usuario.listarPorRolUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://usuario.services.softprog.pucp.edu.pe/Usuario/obtenerPorIdUsuarioRequest", ReplyAction="http://usuario.services.softprog.pucp.edu.pe/Usuario/obtenerPorIdUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftWA.Usuario.obtenerPorIdUsuarioResponse obtenerPorIdUsuario(SoftWA.Usuario.obtenerPorIdUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usuario.services.softprog.pucp.edu.pe/Usuario/obtenerPorIdUsuarioRequest", ReplyAction="http://usuario.services.softprog.pucp.edu.pe/Usuario/obtenerPorIdUsuarioResponse")]
        System.Threading.Tasks.Task<SoftWA.Usuario.obtenerPorIdUsuarioResponse> obtenerPorIdUsuarioAsync(SoftWA.Usuario.obtenerPorIdUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://usuario.services.softprog.pucp.edu.pe/Usuario/listarTodosUsuariosRequest", ReplyAction="http://usuario.services.softprog.pucp.edu.pe/Usuario/listarTodosUsuariosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftWA.Usuario.listarTodosUsuariosResponse listarTodosUsuarios(SoftWA.Usuario.listarTodosUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usuario.services.softprog.pucp.edu.pe/Usuario/listarTodosUsuariosRequest", ReplyAction="http://usuario.services.softprog.pucp.edu.pe/Usuario/listarTodosUsuariosResponse")]
        System.Threading.Tasks.Task<SoftWA.Usuario.listarTodosUsuariosResponse> listarTodosUsuariosAsync(SoftWA.Usuario.listarTodosUsuariosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://usuario.services.softprog.pucp.edu.pe/Usuario/autenticarUsuarioRequest", ReplyAction="http://usuario.services.softprog.pucp.edu.pe/Usuario/autenticarUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftWA.Usuario.autenticarUsuarioResponse autenticarUsuario(SoftWA.Usuario.autenticarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usuario.services.softprog.pucp.edu.pe/Usuario/autenticarUsuarioRequest", ReplyAction="http://usuario.services.softprog.pucp.edu.pe/Usuario/autenticarUsuarioResponse")]
        System.Threading.Tasks.Task<SoftWA.Usuario.autenticarUsuarioResponse> autenticarUsuarioAsync(SoftWA.Usuario.autenticarUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://usuario.services.softprog.pucp.edu.pe/Usuario/insertarUsuarioRequest", ReplyAction="http://usuario.services.softprog.pucp.edu.pe/Usuario/insertarUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftWA.Usuario.insertarUsuarioResponse insertarUsuario(SoftWA.Usuario.insertarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usuario.services.softprog.pucp.edu.pe/Usuario/insertarUsuarioRequest", ReplyAction="http://usuario.services.softprog.pucp.edu.pe/Usuario/insertarUsuarioResponse")]
        System.Threading.Tasks.Task<SoftWA.Usuario.insertarUsuarioResponse> insertarUsuarioAsync(SoftWA.Usuario.insertarUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://usuario.services.softprog.pucp.edu.pe/Usuario/eliminarUsuarioRequest", ReplyAction="http://usuario.services.softprog.pucp.edu.pe/Usuario/eliminarUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftWA.Usuario.eliminarUsuarioResponse eliminarUsuario(SoftWA.Usuario.eliminarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usuario.services.softprog.pucp.edu.pe/Usuario/eliminarUsuarioRequest", ReplyAction="http://usuario.services.softprog.pucp.edu.pe/Usuario/eliminarUsuarioResponse")]
        System.Threading.Tasks.Task<SoftWA.Usuario.eliminarUsuarioResponse> eliminarUsuarioAsync(SoftWA.Usuario.eliminarUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://usuario.services.softprog.pucp.edu.pe/Usuario/modificarUsuarioRequest", ReplyAction="http://usuario.services.softprog.pucp.edu.pe/Usuario/modificarUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftWA.Usuario.modificarUsuarioResponse modificarUsuario(SoftWA.Usuario.modificarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usuario.services.softprog.pucp.edu.pe/Usuario/modificarUsuarioRequest", ReplyAction="http://usuario.services.softprog.pucp.edu.pe/Usuario/modificarUsuarioResponse")]
        System.Threading.Tasks.Task<SoftWA.Usuario.modificarUsuarioResponse> modificarUsuarioAsync(SoftWA.Usuario.modificarUsuarioRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/")]
    public partial class usuarioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private string contraseñaField;
        
        private string emailField;
        
        private int idField;
        
        private rolDTO rolField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                this.contraseñaField = value;
                this.RaisePropertyChanged("contraseña");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public rolDTO rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
                this.RaisePropertyChanged("rol");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/")]
    public partial class rolDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private int idField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarPorEmailUsuario", WrapperNamespace="http://usuario.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class buscarPorEmailUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        public buscarPorEmailUsuarioRequest() {
        }
        
        public buscarPorEmailUsuarioRequest(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarPorEmailUsuarioResponse", WrapperNamespace="http://usuario.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class buscarPorEmailUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftWA.Usuario.usuarioDTO @return;
        
        public buscarPorEmailUsuarioResponse() {
        }
        
        public buscarPorEmailUsuarioResponse(SoftWA.Usuario.usuarioDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorRolUsuario", WrapperNamespace="http://usuario.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPorRolUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int rolId;
        
        public listarPorRolUsuarioRequest() {
        }
        
        public listarPorRolUsuarioRequest(int rolId) {
            this.rolId = rolId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorRolUsuarioResponse", WrapperNamespace="http://usuario.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPorRolUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftWA.Usuario.usuarioDTO[] @return;
        
        public listarPorRolUsuarioResponse() {
        }
        
        public listarPorRolUsuarioResponse(SoftWA.Usuario.usuarioDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdUsuario", WrapperNamespace="http://usuario.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        public obtenerPorIdUsuarioRequest() {
        }
        
        public obtenerPorIdUsuarioRequest(int idUsuario) {
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdUsuarioResponse", WrapperNamespace="http://usuario.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftWA.Usuario.usuarioDTO @return;
        
        public obtenerPorIdUsuarioResponse() {
        }
        
        public obtenerPorIdUsuarioResponse(SoftWA.Usuario.usuarioDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosUsuarios", WrapperNamespace="http://usuario.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosUsuariosRequest {
        
        public listarTodosUsuariosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosUsuariosResponse", WrapperNamespace="http://usuario.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftWA.Usuario.usuarioDTO[] @return;
        
        public listarTodosUsuariosResponse() {
        }
        
        public listarTodosUsuariosResponse(SoftWA.Usuario.usuarioDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="autenticarUsuario", WrapperNamespace="http://usuario.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class autenticarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrasena;
        
        public autenticarUsuarioRequest() {
        }
        
        public autenticarUsuarioRequest(string email, string contrasena) {
            this.email = email;
            this.contrasena = contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="autenticarUsuarioResponse", WrapperNamespace="http://usuario.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class autenticarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftWA.Usuario.usuarioDTO @return;
        
        public autenticarUsuarioResponse() {
        }
        
        public autenticarUsuarioResponse(SoftWA.Usuario.usuarioDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarUsuario", WrapperNamespace="http://usuario.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftWA.Usuario.usuarioDTO usuario;
        
        public insertarUsuarioRequest() {
        }
        
        public insertarUsuarioRequest(SoftWA.Usuario.usuarioDTO usuario) {
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarUsuarioResponse", WrapperNamespace="http://usuario.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarUsuarioResponse() {
        }
        
        public insertarUsuarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarUsuario", WrapperNamespace="http://usuario.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftWA.Usuario.usuarioDTO usuario;
        
        public eliminarUsuarioRequest() {
        }
        
        public eliminarUsuarioRequest(SoftWA.Usuario.usuarioDTO usuario) {
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarUsuarioResponse", WrapperNamespace="http://usuario.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarUsuarioResponse() {
        }
        
        public eliminarUsuarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarUsuario", WrapperNamespace="http://usuario.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftWA.Usuario.usuarioDTO usuario;
        
        public modificarUsuarioRequest() {
        }
        
        public modificarUsuarioRequest(SoftWA.Usuario.usuarioDTO usuario) {
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarUsuarioResponse", WrapperNamespace="http://usuario.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarUsuarioResponse() {
        }
        
        public modificarUsuarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UsuarioChannel : SoftWA.Usuario.Usuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioClient : System.ServiceModel.ClientBase<SoftWA.Usuario.Usuario>, SoftWA.Usuario.Usuario {
        
        public UsuarioClient() {
        }
        
        public UsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftWA.Usuario.buscarPorEmailUsuarioResponse SoftWA.Usuario.Usuario.buscarPorEmailUsuario(SoftWA.Usuario.buscarPorEmailUsuarioRequest request) {
            return base.Channel.buscarPorEmailUsuario(request);
        }
        
        public SoftWA.Usuario.usuarioDTO buscarPorEmailUsuario(string email) {
            SoftWA.Usuario.buscarPorEmailUsuarioRequest inValue = new SoftWA.Usuario.buscarPorEmailUsuarioRequest();
            inValue.email = email;
            SoftWA.Usuario.buscarPorEmailUsuarioResponse retVal = ((SoftWA.Usuario.Usuario)(this)).buscarPorEmailUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftWA.Usuario.buscarPorEmailUsuarioResponse> SoftWA.Usuario.Usuario.buscarPorEmailUsuarioAsync(SoftWA.Usuario.buscarPorEmailUsuarioRequest request) {
            return base.Channel.buscarPorEmailUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftWA.Usuario.buscarPorEmailUsuarioResponse> buscarPorEmailUsuarioAsync(string email) {
            SoftWA.Usuario.buscarPorEmailUsuarioRequest inValue = new SoftWA.Usuario.buscarPorEmailUsuarioRequest();
            inValue.email = email;
            return ((SoftWA.Usuario.Usuario)(this)).buscarPorEmailUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftWA.Usuario.listarPorRolUsuarioResponse SoftWA.Usuario.Usuario.listarPorRolUsuario(SoftWA.Usuario.listarPorRolUsuarioRequest request) {
            return base.Channel.listarPorRolUsuario(request);
        }
        
        public SoftWA.Usuario.usuarioDTO[] listarPorRolUsuario(int rolId) {
            SoftWA.Usuario.listarPorRolUsuarioRequest inValue = new SoftWA.Usuario.listarPorRolUsuarioRequest();
            inValue.rolId = rolId;
            SoftWA.Usuario.listarPorRolUsuarioResponse retVal = ((SoftWA.Usuario.Usuario)(this)).listarPorRolUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftWA.Usuario.listarPorRolUsuarioResponse> SoftWA.Usuario.Usuario.listarPorRolUsuarioAsync(SoftWA.Usuario.listarPorRolUsuarioRequest request) {
            return base.Channel.listarPorRolUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftWA.Usuario.listarPorRolUsuarioResponse> listarPorRolUsuarioAsync(int rolId) {
            SoftWA.Usuario.listarPorRolUsuarioRequest inValue = new SoftWA.Usuario.listarPorRolUsuarioRequest();
            inValue.rolId = rolId;
            return ((SoftWA.Usuario.Usuario)(this)).listarPorRolUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftWA.Usuario.obtenerPorIdUsuarioResponse SoftWA.Usuario.Usuario.obtenerPorIdUsuario(SoftWA.Usuario.obtenerPorIdUsuarioRequest request) {
            return base.Channel.obtenerPorIdUsuario(request);
        }
        
        public SoftWA.Usuario.usuarioDTO obtenerPorIdUsuario(int idUsuario) {
            SoftWA.Usuario.obtenerPorIdUsuarioRequest inValue = new SoftWA.Usuario.obtenerPorIdUsuarioRequest();
            inValue.idUsuario = idUsuario;
            SoftWA.Usuario.obtenerPorIdUsuarioResponse retVal = ((SoftWA.Usuario.Usuario)(this)).obtenerPorIdUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftWA.Usuario.obtenerPorIdUsuarioResponse> SoftWA.Usuario.Usuario.obtenerPorIdUsuarioAsync(SoftWA.Usuario.obtenerPorIdUsuarioRequest request) {
            return base.Channel.obtenerPorIdUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftWA.Usuario.obtenerPorIdUsuarioResponse> obtenerPorIdUsuarioAsync(int idUsuario) {
            SoftWA.Usuario.obtenerPorIdUsuarioRequest inValue = new SoftWA.Usuario.obtenerPorIdUsuarioRequest();
            inValue.idUsuario = idUsuario;
            return ((SoftWA.Usuario.Usuario)(this)).obtenerPorIdUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftWA.Usuario.listarTodosUsuariosResponse SoftWA.Usuario.Usuario.listarTodosUsuarios(SoftWA.Usuario.listarTodosUsuariosRequest request) {
            return base.Channel.listarTodosUsuarios(request);
        }
        
        public SoftWA.Usuario.usuarioDTO[] listarTodosUsuarios() {
            SoftWA.Usuario.listarTodosUsuariosRequest inValue = new SoftWA.Usuario.listarTodosUsuariosRequest();
            SoftWA.Usuario.listarTodosUsuariosResponse retVal = ((SoftWA.Usuario.Usuario)(this)).listarTodosUsuarios(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftWA.Usuario.listarTodosUsuariosResponse> SoftWA.Usuario.Usuario.listarTodosUsuariosAsync(SoftWA.Usuario.listarTodosUsuariosRequest request) {
            return base.Channel.listarTodosUsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftWA.Usuario.listarTodosUsuariosResponse> listarTodosUsuariosAsync() {
            SoftWA.Usuario.listarTodosUsuariosRequest inValue = new SoftWA.Usuario.listarTodosUsuariosRequest();
            return ((SoftWA.Usuario.Usuario)(this)).listarTodosUsuariosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftWA.Usuario.autenticarUsuarioResponse SoftWA.Usuario.Usuario.autenticarUsuario(SoftWA.Usuario.autenticarUsuarioRequest request) {
            return base.Channel.autenticarUsuario(request);
        }
        
        public SoftWA.Usuario.usuarioDTO autenticarUsuario(string email, string contrasena) {
            SoftWA.Usuario.autenticarUsuarioRequest inValue = new SoftWA.Usuario.autenticarUsuarioRequest();
            inValue.email = email;
            inValue.contrasena = contrasena;
            SoftWA.Usuario.autenticarUsuarioResponse retVal = ((SoftWA.Usuario.Usuario)(this)).autenticarUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftWA.Usuario.autenticarUsuarioResponse> SoftWA.Usuario.Usuario.autenticarUsuarioAsync(SoftWA.Usuario.autenticarUsuarioRequest request) {
            return base.Channel.autenticarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftWA.Usuario.autenticarUsuarioResponse> autenticarUsuarioAsync(string email, string contrasena) {
            SoftWA.Usuario.autenticarUsuarioRequest inValue = new SoftWA.Usuario.autenticarUsuarioRequest();
            inValue.email = email;
            inValue.contrasena = contrasena;
            return ((SoftWA.Usuario.Usuario)(this)).autenticarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftWA.Usuario.insertarUsuarioResponse SoftWA.Usuario.Usuario.insertarUsuario(SoftWA.Usuario.insertarUsuarioRequest request) {
            return base.Channel.insertarUsuario(request);
        }
        
        public int insertarUsuario(SoftWA.Usuario.usuarioDTO usuario) {
            SoftWA.Usuario.insertarUsuarioRequest inValue = new SoftWA.Usuario.insertarUsuarioRequest();
            inValue.usuario = usuario;
            SoftWA.Usuario.insertarUsuarioResponse retVal = ((SoftWA.Usuario.Usuario)(this)).insertarUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftWA.Usuario.insertarUsuarioResponse> SoftWA.Usuario.Usuario.insertarUsuarioAsync(SoftWA.Usuario.insertarUsuarioRequest request) {
            return base.Channel.insertarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftWA.Usuario.insertarUsuarioResponse> insertarUsuarioAsync(SoftWA.Usuario.usuarioDTO usuario) {
            SoftWA.Usuario.insertarUsuarioRequest inValue = new SoftWA.Usuario.insertarUsuarioRequest();
            inValue.usuario = usuario;
            return ((SoftWA.Usuario.Usuario)(this)).insertarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftWA.Usuario.eliminarUsuarioResponse SoftWA.Usuario.Usuario.eliminarUsuario(SoftWA.Usuario.eliminarUsuarioRequest request) {
            return base.Channel.eliminarUsuario(request);
        }
        
        public int eliminarUsuario(SoftWA.Usuario.usuarioDTO usuario) {
            SoftWA.Usuario.eliminarUsuarioRequest inValue = new SoftWA.Usuario.eliminarUsuarioRequest();
            inValue.usuario = usuario;
            SoftWA.Usuario.eliminarUsuarioResponse retVal = ((SoftWA.Usuario.Usuario)(this)).eliminarUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftWA.Usuario.eliminarUsuarioResponse> SoftWA.Usuario.Usuario.eliminarUsuarioAsync(SoftWA.Usuario.eliminarUsuarioRequest request) {
            return base.Channel.eliminarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftWA.Usuario.eliminarUsuarioResponse> eliminarUsuarioAsync(SoftWA.Usuario.usuarioDTO usuario) {
            SoftWA.Usuario.eliminarUsuarioRequest inValue = new SoftWA.Usuario.eliminarUsuarioRequest();
            inValue.usuario = usuario;
            return ((SoftWA.Usuario.Usuario)(this)).eliminarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftWA.Usuario.modificarUsuarioResponse SoftWA.Usuario.Usuario.modificarUsuario(SoftWA.Usuario.modificarUsuarioRequest request) {
            return base.Channel.modificarUsuario(request);
        }
        
        public int modificarUsuario(SoftWA.Usuario.usuarioDTO usuario) {
            SoftWA.Usuario.modificarUsuarioRequest inValue = new SoftWA.Usuario.modificarUsuarioRequest();
            inValue.usuario = usuario;
            SoftWA.Usuario.modificarUsuarioResponse retVal = ((SoftWA.Usuario.Usuario)(this)).modificarUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftWA.Usuario.modificarUsuarioResponse> SoftWA.Usuario.Usuario.modificarUsuarioAsync(SoftWA.Usuario.modificarUsuarioRequest request) {
            return base.Channel.modificarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftWA.Usuario.modificarUsuarioResponse> modificarUsuarioAsync(SoftWA.Usuario.usuarioDTO usuario) {
            SoftWA.Usuario.modificarUsuarioRequest inValue = new SoftWA.Usuario.modificarUsuarioRequest();
            inValue.usuario = usuario;
            return ((SoftWA.Usuario.Usuario)(this)).modificarUsuarioAsync(inValue);
        }
    }
}
