//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftWA.Carrito {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/", ConfigurationName="Carrito.Carrito")]
    public interface Carrito {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://pedido.services.softprog.pucp.edu.pe/Carrito/obtenerPorIdCarritoRequest", ReplyAction="http://pedido.services.softprog.pucp.edu.pe/Carrito/obtenerPorIdCarritoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftWA.Carrito.obtenerPorIdCarritoResponse obtenerPorIdCarrito(SoftWA.Carrito.obtenerPorIdCarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pedido.services.softprog.pucp.edu.pe/Carrito/obtenerPorIdCarritoRequest", ReplyAction="http://pedido.services.softprog.pucp.edu.pe/Carrito/obtenerPorIdCarritoResponse")]
        System.Threading.Tasks.Task<SoftWA.Carrito.obtenerPorIdCarritoResponse> obtenerPorIdCarritoAsync(SoftWA.Carrito.obtenerPorIdCarritoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://pedido.services.softprog.pucp.edu.pe/Carrito/insertarCarritoRequest", ReplyAction="http://pedido.services.softprog.pucp.edu.pe/Carrito/insertarCarritoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftWA.Carrito.insertarCarritoResponse insertarCarrito(SoftWA.Carrito.insertarCarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pedido.services.softprog.pucp.edu.pe/Carrito/insertarCarritoRequest", ReplyAction="http://pedido.services.softprog.pucp.edu.pe/Carrito/insertarCarritoResponse")]
        System.Threading.Tasks.Task<SoftWA.Carrito.insertarCarritoResponse> insertarCarritoAsync(SoftWA.Carrito.insertarCarritoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://pedido.services.softprog.pucp.edu.pe/Carrito/modificarCarritoRequest", ReplyAction="http://pedido.services.softprog.pucp.edu.pe/Carrito/modificarCarritoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftWA.Carrito.modificarCarritoResponse modificarCarrito(SoftWA.Carrito.modificarCarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pedido.services.softprog.pucp.edu.pe/Carrito/modificarCarritoRequest", ReplyAction="http://pedido.services.softprog.pucp.edu.pe/Carrito/modificarCarritoResponse")]
        System.Threading.Tasks.Task<SoftWA.Carrito.modificarCarritoResponse> modificarCarritoAsync(SoftWA.Carrito.modificarCarritoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://pedido.services.softprog.pucp.edu.pe/Carrito/listarTodosCarritoRequest", ReplyAction="http://pedido.services.softprog.pucp.edu.pe/Carrito/listarTodosCarritoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftWA.Carrito.listarTodosCarritoResponse listarTodosCarrito(SoftWA.Carrito.listarTodosCarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pedido.services.softprog.pucp.edu.pe/Carrito/listarTodosCarritoRequest", ReplyAction="http://pedido.services.softprog.pucp.edu.pe/Carrito/listarTodosCarritoResponse")]
        System.Threading.Tasks.Task<SoftWA.Carrito.listarTodosCarritoResponse> listarTodosCarritoAsync(SoftWA.Carrito.listarTodosCarritoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://pedido.services.softprog.pucp.edu.pe/Carrito/eliminarCarritoRequest", ReplyAction="http://pedido.services.softprog.pucp.edu.pe/Carrito/eliminarCarritoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftWA.Carrito.eliminarCarritoResponse eliminarCarrito(SoftWA.Carrito.eliminarCarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pedido.services.softprog.pucp.edu.pe/Carrito/eliminarCarritoRequest", ReplyAction="http://pedido.services.softprog.pucp.edu.pe/Carrito/eliminarCarritoResponse")]
        System.Threading.Tasks.Task<SoftWA.Carrito.eliminarCarritoResponse> eliminarCarritoAsync(SoftWA.Carrito.eliminarCarritoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/")]
    public partial class carritoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private localDateTime fechaActualizacionField;
        
        private localDateTime fechaCreacionField;
        
        private int idCarritoField;
        
        private itemCarritoDTO[] itemsField;
        
        private personaDTO personaField;
        
        private double totalField;
        
        private usuarioDTO usuarioActualizacionField;
        
        private usuarioDTO usuarioCreacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public localDateTime fechaActualizacion {
            get {
                return this.fechaActualizacionField;
            }
            set {
                this.fechaActualizacionField = value;
                this.RaisePropertyChanged("fechaActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public localDateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idCarrito {
            get {
                return this.idCarritoField;
            }
            set {
                this.idCarritoField = value;
                this.RaisePropertyChanged("idCarrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("items", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public itemCarritoDTO[] items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public personaDTO persona {
            get {
                return this.personaField;
            }
            set {
                this.personaField = value;
                this.RaisePropertyChanged("persona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public usuarioDTO usuarioActualizacion {
            get {
                return this.usuarioActualizacionField;
            }
            set {
                this.usuarioActualizacionField = value;
                this.RaisePropertyChanged("usuarioActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public usuarioDTO usuarioCreacion {
            get {
                return this.usuarioCreacionField;
            }
            set {
                this.usuarioCreacionField = value;
                this.RaisePropertyChanged("usuarioCreacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/")]
    public partial class localDateTime : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/")]
    public partial class direccionDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private string aliasField;
        
        private string ciudadField;
        
        private string direccionField;
        
        private localDateTime fechaActualizacionField;
        
        private localDateTime fechaCreacionField;
        
        private int idField;
        
        private personaDTO personaIdField;
        
        private string referenciaField;
        
        private usuarioDTO usuarioActualizacionField;
        
        private usuarioDTO usuarioCreacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
                this.RaisePropertyChanged("alias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ciudad {
            get {
                return this.ciudadField;
            }
            set {
                this.ciudadField = value;
                this.RaisePropertyChanged("ciudad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public localDateTime fechaActualizacion {
            get {
                return this.fechaActualizacionField;
            }
            set {
                this.fechaActualizacionField = value;
                this.RaisePropertyChanged("fechaActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public localDateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public personaDTO personaId {
            get {
                return this.personaIdField;
            }
            set {
                this.personaIdField = value;
                this.RaisePropertyChanged("personaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
                this.RaisePropertyChanged("referencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public usuarioDTO usuarioActualizacion {
            get {
                return this.usuarioActualizacionField;
            }
            set {
                this.usuarioActualizacionField = value;
                this.RaisePropertyChanged("usuarioActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public usuarioDTO usuarioCreacion {
            get {
                return this.usuarioCreacionField;
            }
            set {
                this.usuarioCreacionField = value;
                this.RaisePropertyChanged("usuarioCreacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/")]
    public partial class personaDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private string apellidosField;
        
        private direccionDTO[] direccionesField;
        
        private localDateTime fechaActualizacionField;
        
        private localDateTime fechaCreacionField;
        
        private int idField;
        
        private string nombresField;
        
        private string telefonoField;
        
        private usuarioDTO usuarioField;
        
        private usuarioDTO usuarioActualizacionField;
        
        private usuarioDTO usuarioCreacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("direcciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public direccionDTO[] direcciones {
            get {
                return this.direccionesField;
            }
            set {
                this.direccionesField = value;
                this.RaisePropertyChanged("direcciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public localDateTime fechaActualizacion {
            get {
                return this.fechaActualizacionField;
            }
            set {
                this.fechaActualizacionField = value;
                this.RaisePropertyChanged("fechaActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public localDateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public usuarioDTO usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public usuarioDTO usuarioActualizacion {
            get {
                return this.usuarioActualizacionField;
            }
            set {
                this.usuarioActualizacionField = value;
                this.RaisePropertyChanged("usuarioActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public usuarioDTO usuarioCreacion {
            get {
                return this.usuarioCreacionField;
            }
            set {
                this.usuarioCreacionField = value;
                this.RaisePropertyChanged("usuarioCreacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/")]
    public partial class usuarioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private string contraseñaField;
        
        private string emailField;
        
        private int idField;
        
        private rolDTO rolField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                this.contraseñaField = value;
                this.RaisePropertyChanged("contraseña");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public rolDTO rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
                this.RaisePropertyChanged("rol");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/")]
    public partial class rolDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private int idField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/")]
    public partial class precioPresentacionDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private int cantidadField;
        
        private localDateTime fechaActualizacionField;
        
        private localDateTime fechaCreacionField;
        
        private int idPrecioPresentacionField;
        
        private double precioField;
        
        private productoDTO productoField;
        
        private tipoMedida tipoMedidaField;
        
        private bool tipoMedidaFieldSpecified;
        
        private usuarioDTO usuarioActualizacionField;
        
        private usuarioDTO usuarioCreacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public localDateTime fechaActualizacion {
            get {
                return this.fechaActualizacionField;
            }
            set {
                this.fechaActualizacionField = value;
                this.RaisePropertyChanged("fechaActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public localDateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idPrecioPresentacion {
            get {
                return this.idPrecioPresentacionField;
            }
            set {
                this.idPrecioPresentacionField = value;
                this.RaisePropertyChanged("idPrecioPresentacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public productoDTO producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public tipoMedida tipoMedida {
            get {
                return this.tipoMedidaField;
            }
            set {
                this.tipoMedidaField = value;
                this.RaisePropertyChanged("tipoMedida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoMedidaSpecified {
            get {
                return this.tipoMedidaFieldSpecified;
            }
            set {
                this.tipoMedidaFieldSpecified = value;
                this.RaisePropertyChanged("tipoMedidaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public usuarioDTO usuarioActualizacion {
            get {
                return this.usuarioActualizacionField;
            }
            set {
                this.usuarioActualizacionField = value;
                this.RaisePropertyChanged("usuarioActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public usuarioDTO usuarioCreacion {
            get {
                return this.usuarioCreacionField;
            }
            set {
                this.usuarioCreacionField = value;
                this.RaisePropertyChanged("usuarioCreacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/")]
    public partial class productoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private string categoriaField;
        
        private string descripcionField;
        
        private localDateTime fechaActualizacionField;
        
        private localDateTime fechaCreacionField;
        
        private int idProductoField;
        
        private string nombreField;
        
        private double precioField;
        
        private precioPresentacionDTO[] preciosPorPresentacionesField;
        
        private int stockField;
        
        private usuarioDTO usuarioActualizacionField;
        
        private usuarioDTO usuarioCreacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public localDateTime fechaActualizacion {
            get {
                return this.fechaActualizacionField;
            }
            set {
                this.fechaActualizacionField = value;
                this.RaisePropertyChanged("fechaActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public localDateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
                this.RaisePropertyChanged("idProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("preciosPorPresentaciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public precioPresentacionDTO[] preciosPorPresentaciones {
            get {
                return this.preciosPorPresentacionesField;
            }
            set {
                this.preciosPorPresentacionesField = value;
                this.RaisePropertyChanged("preciosPorPresentaciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
                this.RaisePropertyChanged("stock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public usuarioDTO usuarioActualizacion {
            get {
                return this.usuarioActualizacionField;
            }
            set {
                this.usuarioActualizacionField = value;
                this.RaisePropertyChanged("usuarioActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public usuarioDTO usuarioCreacion {
            get {
                return this.usuarioCreacionField;
            }
            set {
                this.usuarioCreacionField = value;
                this.RaisePropertyChanged("usuarioCreacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/")]
    public enum tipoMedida {
        
        /// <remarks/>
        DECENA,
        
        /// <remarks/>
        DOCENA,
        
        /// <remarks/>
        CENTENA,
        
        /// <remarks/>
        MILLAR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/")]
    public partial class itemCarritoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private int cantidadField;
        
        private carritoDTO carritoField;
        
        private localDateTime fechaActualizacionField;
        
        private localDateTime fechaCreacionField;
        
        private int idItemCarritoField;
        
        private productoDTO productoField;
        
        private double subtotalField;
        
        private usuarioDTO usuarioActualizacionField;
        
        private usuarioDTO usuarioCreacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public carritoDTO carrito {
            get {
                return this.carritoField;
            }
            set {
                this.carritoField = value;
                this.RaisePropertyChanged("carrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public localDateTime fechaActualizacion {
            get {
                return this.fechaActualizacionField;
            }
            set {
                this.fechaActualizacionField = value;
                this.RaisePropertyChanged("fechaActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public localDateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idItemCarrito {
            get {
                return this.idItemCarritoField;
            }
            set {
                this.idItemCarritoField = value;
                this.RaisePropertyChanged("idItemCarrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public productoDTO producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double subtotal {
            get {
                return this.subtotalField;
            }
            set {
                this.subtotalField = value;
                this.RaisePropertyChanged("subtotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public usuarioDTO usuarioActualizacion {
            get {
                return this.usuarioActualizacionField;
            }
            set {
                this.usuarioActualizacionField = value;
                this.RaisePropertyChanged("usuarioActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public usuarioDTO usuarioCreacion {
            get {
                return this.usuarioCreacionField;
            }
            set {
                this.usuarioCreacionField = value;
                this.RaisePropertyChanged("usuarioCreacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdCarrito", WrapperNamespace="http://pedido.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdCarritoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCarrito;
        
        public obtenerPorIdCarritoRequest() {
        }
        
        public obtenerPorIdCarritoRequest(int idCarrito) {
            this.idCarrito = idCarrito;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdCarritoResponse", WrapperNamespace="http://pedido.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdCarritoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftWA.Carrito.carritoDTO @return;
        
        public obtenerPorIdCarritoResponse() {
        }
        
        public obtenerPorIdCarritoResponse(SoftWA.Carrito.carritoDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCarrito", WrapperNamespace="http://pedido.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarCarritoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftWA.Carrito.carritoDTO carrito;
        
        public insertarCarritoRequest() {
        }
        
        public insertarCarritoRequest(SoftWA.Carrito.carritoDTO carrito) {
            this.carrito = carrito;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCarritoResponse", WrapperNamespace="http://pedido.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarCarritoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarCarritoResponse() {
        }
        
        public insertarCarritoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarCarrito", WrapperNamespace="http://pedido.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarCarritoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftWA.Carrito.carritoDTO carrito;
        
        public modificarCarritoRequest() {
        }
        
        public modificarCarritoRequest(SoftWA.Carrito.carritoDTO carrito) {
            this.carrito = carrito;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarCarritoResponse", WrapperNamespace="http://pedido.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarCarritoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarCarritoResponse() {
        }
        
        public modificarCarritoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosCarrito", WrapperNamespace="http://pedido.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosCarritoRequest {
        
        public listarTodosCarritoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosCarritoResponse", WrapperNamespace="http://pedido.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosCarritoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftWA.Carrito.carritoDTO[] @return;
        
        public listarTodosCarritoResponse() {
        }
        
        public listarTodosCarritoResponse(SoftWA.Carrito.carritoDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCarrito", WrapperNamespace="http://pedido.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCarritoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftWA.Carrito.carritoDTO carrito;
        
        public eliminarCarritoRequest() {
        }
        
        public eliminarCarritoRequest(SoftWA.Carrito.carritoDTO carrito) {
            this.carrito = carrito;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCarritoResponse", WrapperNamespace="http://pedido.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCarritoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarCarritoResponse() {
        }
        
        public eliminarCarritoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CarritoChannel : SoftWA.Carrito.Carrito, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarritoClient : System.ServiceModel.ClientBase<SoftWA.Carrito.Carrito>, SoftWA.Carrito.Carrito {
        
        public CarritoClient() {
        }
        
        public CarritoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarritoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarritoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarritoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftWA.Carrito.obtenerPorIdCarritoResponse SoftWA.Carrito.Carrito.obtenerPorIdCarrito(SoftWA.Carrito.obtenerPorIdCarritoRequest request) {
            return base.Channel.obtenerPorIdCarrito(request);
        }
        
        public SoftWA.Carrito.carritoDTO obtenerPorIdCarrito(int idCarrito) {
            SoftWA.Carrito.obtenerPorIdCarritoRequest inValue = new SoftWA.Carrito.obtenerPorIdCarritoRequest();
            inValue.idCarrito = idCarrito;
            SoftWA.Carrito.obtenerPorIdCarritoResponse retVal = ((SoftWA.Carrito.Carrito)(this)).obtenerPorIdCarrito(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftWA.Carrito.obtenerPorIdCarritoResponse> SoftWA.Carrito.Carrito.obtenerPorIdCarritoAsync(SoftWA.Carrito.obtenerPorIdCarritoRequest request) {
            return base.Channel.obtenerPorIdCarritoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftWA.Carrito.obtenerPorIdCarritoResponse> obtenerPorIdCarritoAsync(int idCarrito) {
            SoftWA.Carrito.obtenerPorIdCarritoRequest inValue = new SoftWA.Carrito.obtenerPorIdCarritoRequest();
            inValue.idCarrito = idCarrito;
            return ((SoftWA.Carrito.Carrito)(this)).obtenerPorIdCarritoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftWA.Carrito.insertarCarritoResponse SoftWA.Carrito.Carrito.insertarCarrito(SoftWA.Carrito.insertarCarritoRequest request) {
            return base.Channel.insertarCarrito(request);
        }
        
        public int insertarCarrito(SoftWA.Carrito.carritoDTO carrito) {
            SoftWA.Carrito.insertarCarritoRequest inValue = new SoftWA.Carrito.insertarCarritoRequest();
            inValue.carrito = carrito;
            SoftWA.Carrito.insertarCarritoResponse retVal = ((SoftWA.Carrito.Carrito)(this)).insertarCarrito(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftWA.Carrito.insertarCarritoResponse> SoftWA.Carrito.Carrito.insertarCarritoAsync(SoftWA.Carrito.insertarCarritoRequest request) {
            return base.Channel.insertarCarritoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftWA.Carrito.insertarCarritoResponse> insertarCarritoAsync(SoftWA.Carrito.carritoDTO carrito) {
            SoftWA.Carrito.insertarCarritoRequest inValue = new SoftWA.Carrito.insertarCarritoRequest();
            inValue.carrito = carrito;
            return ((SoftWA.Carrito.Carrito)(this)).insertarCarritoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftWA.Carrito.modificarCarritoResponse SoftWA.Carrito.Carrito.modificarCarrito(SoftWA.Carrito.modificarCarritoRequest request) {
            return base.Channel.modificarCarrito(request);
        }
        
        public int modificarCarrito(SoftWA.Carrito.carritoDTO carrito) {
            SoftWA.Carrito.modificarCarritoRequest inValue = new SoftWA.Carrito.modificarCarritoRequest();
            inValue.carrito = carrito;
            SoftWA.Carrito.modificarCarritoResponse retVal = ((SoftWA.Carrito.Carrito)(this)).modificarCarrito(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftWA.Carrito.modificarCarritoResponse> SoftWA.Carrito.Carrito.modificarCarritoAsync(SoftWA.Carrito.modificarCarritoRequest request) {
            return base.Channel.modificarCarritoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftWA.Carrito.modificarCarritoResponse> modificarCarritoAsync(SoftWA.Carrito.carritoDTO carrito) {
            SoftWA.Carrito.modificarCarritoRequest inValue = new SoftWA.Carrito.modificarCarritoRequest();
            inValue.carrito = carrito;
            return ((SoftWA.Carrito.Carrito)(this)).modificarCarritoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftWA.Carrito.listarTodosCarritoResponse SoftWA.Carrito.Carrito.listarTodosCarrito(SoftWA.Carrito.listarTodosCarritoRequest request) {
            return base.Channel.listarTodosCarrito(request);
        }
        
        public SoftWA.Carrito.carritoDTO[] listarTodosCarrito() {
            SoftWA.Carrito.listarTodosCarritoRequest inValue = new SoftWA.Carrito.listarTodosCarritoRequest();
            SoftWA.Carrito.listarTodosCarritoResponse retVal = ((SoftWA.Carrito.Carrito)(this)).listarTodosCarrito(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftWA.Carrito.listarTodosCarritoResponse> SoftWA.Carrito.Carrito.listarTodosCarritoAsync(SoftWA.Carrito.listarTodosCarritoRequest request) {
            return base.Channel.listarTodosCarritoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftWA.Carrito.listarTodosCarritoResponse> listarTodosCarritoAsync() {
            SoftWA.Carrito.listarTodosCarritoRequest inValue = new SoftWA.Carrito.listarTodosCarritoRequest();
            return ((SoftWA.Carrito.Carrito)(this)).listarTodosCarritoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftWA.Carrito.eliminarCarritoResponse SoftWA.Carrito.Carrito.eliminarCarrito(SoftWA.Carrito.eliminarCarritoRequest request) {
            return base.Channel.eliminarCarrito(request);
        }
        
        public int eliminarCarrito(SoftWA.Carrito.carritoDTO carrito) {
            SoftWA.Carrito.eliminarCarritoRequest inValue = new SoftWA.Carrito.eliminarCarritoRequest();
            inValue.carrito = carrito;
            SoftWA.Carrito.eliminarCarritoResponse retVal = ((SoftWA.Carrito.Carrito)(this)).eliminarCarrito(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftWA.Carrito.eliminarCarritoResponse> SoftWA.Carrito.Carrito.eliminarCarritoAsync(SoftWA.Carrito.eliminarCarritoRequest request) {
            return base.Channel.eliminarCarritoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftWA.Carrito.eliminarCarritoResponse> eliminarCarritoAsync(SoftWA.Carrito.carritoDTO carrito) {
            SoftWA.Carrito.eliminarCarritoRequest inValue = new SoftWA.Carrito.eliminarCarritoRequest();
            inValue.carrito = carrito;
            return ((SoftWA.Carrito.Carrito)(this)).eliminarCarritoAsync(inValue);
        }
    }
}
