//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftWA.Rol {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", ConfigurationName="Rol.Rol")]
    public interface Rol {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://usuario.services.softprog.pucp.edu.pe/Rol/insertarRolRequest", ReplyAction="http://usuario.services.softprog.pucp.edu.pe/Rol/insertarRolResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftWA.Rol.insertarRolResponse insertarRol(SoftWA.Rol.insertarRolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usuario.services.softprog.pucp.edu.pe/Rol/insertarRolRequest", ReplyAction="http://usuario.services.softprog.pucp.edu.pe/Rol/insertarRolResponse")]
        System.Threading.Tasks.Task<SoftWA.Rol.insertarRolResponse> insertarRolAsync(SoftWA.Rol.insertarRolRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://usuario.services.softprog.pucp.edu.pe/Rol/modificarRolRequest", ReplyAction="http://usuario.services.softprog.pucp.edu.pe/Rol/modificarRolResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftWA.Rol.modificarRolResponse modificarRol(SoftWA.Rol.modificarRolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usuario.services.softprog.pucp.edu.pe/Rol/modificarRolRequest", ReplyAction="http://usuario.services.softprog.pucp.edu.pe/Rol/modificarRolResponse")]
        System.Threading.Tasks.Task<SoftWA.Rol.modificarRolResponse> modificarRolAsync(SoftWA.Rol.modificarRolRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://usuario.services.softprog.pucp.edu.pe/Rol/listarTodosRolesRequest", ReplyAction="http://usuario.services.softprog.pucp.edu.pe/Rol/listarTodosRolesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftWA.Rol.listarTodosRolesResponse listarTodosRoles(SoftWA.Rol.listarTodosRolesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usuario.services.softprog.pucp.edu.pe/Rol/listarTodosRolesRequest", ReplyAction="http://usuario.services.softprog.pucp.edu.pe/Rol/listarTodosRolesResponse")]
        System.Threading.Tasks.Task<SoftWA.Rol.listarTodosRolesResponse> listarTodosRolesAsync(SoftWA.Rol.listarTodosRolesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://usuario.services.softprog.pucp.edu.pe/Rol/obtenerPorIdRolRequest", ReplyAction="http://usuario.services.softprog.pucp.edu.pe/Rol/obtenerPorIdRolResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftWA.Rol.obtenerPorIdRolResponse obtenerPorIdRol(SoftWA.Rol.obtenerPorIdRolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usuario.services.softprog.pucp.edu.pe/Rol/obtenerPorIdRolRequest", ReplyAction="http://usuario.services.softprog.pucp.edu.pe/Rol/obtenerPorIdRolResponse")]
        System.Threading.Tasks.Task<SoftWA.Rol.obtenerPorIdRolResponse> obtenerPorIdRolAsync(SoftWA.Rol.obtenerPorIdRolRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarRol", WrapperNamespace="http://usuario.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarRolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public insertarRolRequest() {
        }
        
        public insertarRolRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarRolResponse", WrapperNamespace="http://usuario.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarRolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarRolResponse() {
        }
        
        public insertarRolResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarRol", WrapperNamespace="http://usuario.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarRolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int rolId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public modificarRolRequest() {
        }
        
        public modificarRolRequest(int rolId, string nombre) {
            this.rolId = rolId;
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarRolResponse", WrapperNamespace="http://usuario.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarRolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarRolResponse() {
        }
        
        public modificarRolResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/")]
    public partial class rolDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private int idField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosRoles", WrapperNamespace="http://usuario.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosRolesRequest {
        
        public listarTodosRolesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosRolesResponse", WrapperNamespace="http://usuario.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosRolesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftWA.Rol.rolDTO[] @return;
        
        public listarTodosRolesResponse() {
        }
        
        public listarTodosRolesResponse(SoftWA.Rol.rolDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdRol", WrapperNamespace="http://usuario.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdRolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int rolId;
        
        public obtenerPorIdRolRequest() {
        }
        
        public obtenerPorIdRolRequest(int rolId) {
            this.rolId = rolId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdRolResponse", WrapperNamespace="http://usuario.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdRolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftWA.Rol.rolDTO @return;
        
        public obtenerPorIdRolResponse() {
        }
        
        public obtenerPorIdRolResponse(SoftWA.Rol.rolDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RolChannel : SoftWA.Rol.Rol, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RolClient : System.ServiceModel.ClientBase<SoftWA.Rol.Rol>, SoftWA.Rol.Rol {
        
        public RolClient() {
        }
        
        public RolClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RolClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RolClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RolClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftWA.Rol.insertarRolResponse SoftWA.Rol.Rol.insertarRol(SoftWA.Rol.insertarRolRequest request) {
            return base.Channel.insertarRol(request);
        }
        
        public int insertarRol(string nombre) {
            SoftWA.Rol.insertarRolRequest inValue = new SoftWA.Rol.insertarRolRequest();
            inValue.nombre = nombre;
            SoftWA.Rol.insertarRolResponse retVal = ((SoftWA.Rol.Rol)(this)).insertarRol(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftWA.Rol.insertarRolResponse> SoftWA.Rol.Rol.insertarRolAsync(SoftWA.Rol.insertarRolRequest request) {
            return base.Channel.insertarRolAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftWA.Rol.insertarRolResponse> insertarRolAsync(string nombre) {
            SoftWA.Rol.insertarRolRequest inValue = new SoftWA.Rol.insertarRolRequest();
            inValue.nombre = nombre;
            return ((SoftWA.Rol.Rol)(this)).insertarRolAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftWA.Rol.modificarRolResponse SoftWA.Rol.Rol.modificarRol(SoftWA.Rol.modificarRolRequest request) {
            return base.Channel.modificarRol(request);
        }
        
        public int modificarRol(int rolId, string nombre) {
            SoftWA.Rol.modificarRolRequest inValue = new SoftWA.Rol.modificarRolRequest();
            inValue.rolId = rolId;
            inValue.nombre = nombre;
            SoftWA.Rol.modificarRolResponse retVal = ((SoftWA.Rol.Rol)(this)).modificarRol(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftWA.Rol.modificarRolResponse> SoftWA.Rol.Rol.modificarRolAsync(SoftWA.Rol.modificarRolRequest request) {
            return base.Channel.modificarRolAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftWA.Rol.modificarRolResponse> modificarRolAsync(int rolId, string nombre) {
            SoftWA.Rol.modificarRolRequest inValue = new SoftWA.Rol.modificarRolRequest();
            inValue.rolId = rolId;
            inValue.nombre = nombre;
            return ((SoftWA.Rol.Rol)(this)).modificarRolAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftWA.Rol.listarTodosRolesResponse SoftWA.Rol.Rol.listarTodosRoles(SoftWA.Rol.listarTodosRolesRequest request) {
            return base.Channel.listarTodosRoles(request);
        }
        
        public SoftWA.Rol.rolDTO[] listarTodosRoles() {
            SoftWA.Rol.listarTodosRolesRequest inValue = new SoftWA.Rol.listarTodosRolesRequest();
            SoftWA.Rol.listarTodosRolesResponse retVal = ((SoftWA.Rol.Rol)(this)).listarTodosRoles(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftWA.Rol.listarTodosRolesResponse> SoftWA.Rol.Rol.listarTodosRolesAsync(SoftWA.Rol.listarTodosRolesRequest request) {
            return base.Channel.listarTodosRolesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftWA.Rol.listarTodosRolesResponse> listarTodosRolesAsync() {
            SoftWA.Rol.listarTodosRolesRequest inValue = new SoftWA.Rol.listarTodosRolesRequest();
            return ((SoftWA.Rol.Rol)(this)).listarTodosRolesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftWA.Rol.obtenerPorIdRolResponse SoftWA.Rol.Rol.obtenerPorIdRol(SoftWA.Rol.obtenerPorIdRolRequest request) {
            return base.Channel.obtenerPorIdRol(request);
        }
        
        public SoftWA.Rol.rolDTO obtenerPorIdRol(int rolId) {
            SoftWA.Rol.obtenerPorIdRolRequest inValue = new SoftWA.Rol.obtenerPorIdRolRequest();
            inValue.rolId = rolId;
            SoftWA.Rol.obtenerPorIdRolResponse retVal = ((SoftWA.Rol.Rol)(this)).obtenerPorIdRol(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftWA.Rol.obtenerPorIdRolResponse> SoftWA.Rol.Rol.obtenerPorIdRolAsync(SoftWA.Rol.obtenerPorIdRolRequest request) {
            return base.Channel.obtenerPorIdRolAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftWA.Rol.obtenerPorIdRolResponse> obtenerPorIdRolAsync(int rolId) {
            SoftWA.Rol.obtenerPorIdRolRequest inValue = new SoftWA.Rol.obtenerPorIdRolRequest();
            inValue.rolId = rolId;
            return ((SoftWA.Rol.Rol)(this)).obtenerPorIdRolAsync(inValue);
        }
    }
}
