//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftWA.Direccion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", ConfigurationName="Direccion.Direccion")]
    public interface Direccion {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://usuario.services.softprog.pucp.edu.pe/Direccion/insertarDireccionRequest", ReplyAction="http://usuario.services.softprog.pucp.edu.pe/Direccion/insertarDireccionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftWA.Direccion.insertarDireccionResponse insertarDireccion(SoftWA.Direccion.insertarDireccionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usuario.services.softprog.pucp.edu.pe/Direccion/insertarDireccionRequest", ReplyAction="http://usuario.services.softprog.pucp.edu.pe/Direccion/insertarDireccionResponse")]
        System.Threading.Tasks.Task<SoftWA.Direccion.insertarDireccionResponse> insertarDireccionAsync(SoftWA.Direccion.insertarDireccionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://usuario.services.softprog.pucp.edu.pe/Direccion/modificarDireccionRequest", ReplyAction="http://usuario.services.softprog.pucp.edu.pe/Direccion/modificarDireccionResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftWA.Direccion.modificarDireccionResponse modificarDireccion(SoftWA.Direccion.modificarDireccionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usuario.services.softprog.pucp.edu.pe/Direccion/modificarDireccionRequest", ReplyAction="http://usuario.services.softprog.pucp.edu.pe/Direccion/modificarDireccionResponse" +
            "")]
        System.Threading.Tasks.Task<SoftWA.Direccion.modificarDireccionResponse> modificarDireccionAsync(SoftWA.Direccion.modificarDireccionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://usuario.services.softprog.pucp.edu.pe/Direccion/eliminarDireccionRequest", ReplyAction="http://usuario.services.softprog.pucp.edu.pe/Direccion/eliminarDireccionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftWA.Direccion.eliminarDireccionResponse eliminarDireccion(SoftWA.Direccion.eliminarDireccionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usuario.services.softprog.pucp.edu.pe/Direccion/eliminarDireccionRequest", ReplyAction="http://usuario.services.softprog.pucp.edu.pe/Direccion/eliminarDireccionResponse")]
        System.Threading.Tasks.Task<SoftWA.Direccion.eliminarDireccionResponse> eliminarDireccionAsync(SoftWA.Direccion.eliminarDireccionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://usuario.services.softprog.pucp.edu.pe/Direccion/obtenerPorIdDireccionReque" +
            "st", ReplyAction="http://usuario.services.softprog.pucp.edu.pe/Direccion/obtenerPorIdDireccionRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftWA.Direccion.obtenerPorIdDireccionResponse obtenerPorIdDireccion(SoftWA.Direccion.obtenerPorIdDireccionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usuario.services.softprog.pucp.edu.pe/Direccion/obtenerPorIdDireccionReque" +
            "st", ReplyAction="http://usuario.services.softprog.pucp.edu.pe/Direccion/obtenerPorIdDireccionRespo" +
            "nse")]
        System.Threading.Tasks.Task<SoftWA.Direccion.obtenerPorIdDireccionResponse> obtenerPorIdDireccionAsync(SoftWA.Direccion.obtenerPorIdDireccionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://usuario.services.softprog.pucp.edu.pe/Direccion/listarTodosDireccionReques" +
            "t", ReplyAction="http://usuario.services.softprog.pucp.edu.pe/Direccion/listarTodosDireccionRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftWA.Direccion.listarTodosDireccionResponse listarTodosDireccion(SoftWA.Direccion.listarTodosDireccionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usuario.services.softprog.pucp.edu.pe/Direccion/listarTodosDireccionReques" +
            "t", ReplyAction="http://usuario.services.softprog.pucp.edu.pe/Direccion/listarTodosDireccionRespon" +
            "se")]
        System.Threading.Tasks.Task<SoftWA.Direccion.listarTodosDireccionResponse> listarTodosDireccionAsync(SoftWA.Direccion.listarTodosDireccionRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/")]
    public partial class direccionDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private string aliasField;
        
        private string ciudadField;
        
        private string direccionField;
        
        private localDateTime fechaActualizacionField;
        
        private localDateTime fechaCreacionField;
        
        private int idField;
        
        private personaDTO personaIdField;
        
        private string referenciaField;
        
        private usuarioDTO usuarioActualizacionField;
        
        private usuarioDTO usuarioCreacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
                this.RaisePropertyChanged("alias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ciudad {
            get {
                return this.ciudadField;
            }
            set {
                this.ciudadField = value;
                this.RaisePropertyChanged("ciudad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public localDateTime fechaActualizacion {
            get {
                return this.fechaActualizacionField;
            }
            set {
                this.fechaActualizacionField = value;
                this.RaisePropertyChanged("fechaActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public localDateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public personaDTO personaId {
            get {
                return this.personaIdField;
            }
            set {
                this.personaIdField = value;
                this.RaisePropertyChanged("personaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
                this.RaisePropertyChanged("referencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public usuarioDTO usuarioActualizacion {
            get {
                return this.usuarioActualizacionField;
            }
            set {
                this.usuarioActualizacionField = value;
                this.RaisePropertyChanged("usuarioActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public usuarioDTO usuarioCreacion {
            get {
                return this.usuarioCreacionField;
            }
            set {
                this.usuarioCreacionField = value;
                this.RaisePropertyChanged("usuarioCreacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/")]
    public partial class localDateTime : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/")]
    public partial class rolDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private int idField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/")]
    public partial class usuarioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private string contraseñaField;
        
        private string emailField;
        
        private int idField;
        
        private rolDTO rolField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                this.contraseñaField = value;
                this.RaisePropertyChanged("contraseña");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public rolDTO rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
                this.RaisePropertyChanged("rol");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/")]
    public partial class personaDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private string apellidosField;
        
        private direccionDTO[] direccionesField;
        
        private localDateTime fechaActualizacionField;
        
        private localDateTime fechaCreacionField;
        
        private int idField;
        
        private string nombresField;
        
        private string telefonoField;
        
        private usuarioDTO usuarioField;
        
        private usuarioDTO usuarioActualizacionField;
        
        private usuarioDTO usuarioCreacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("direcciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public direccionDTO[] direcciones {
            get {
                return this.direccionesField;
            }
            set {
                this.direccionesField = value;
                this.RaisePropertyChanged("direcciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public localDateTime fechaActualizacion {
            get {
                return this.fechaActualizacionField;
            }
            set {
                this.fechaActualizacionField = value;
                this.RaisePropertyChanged("fechaActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public localDateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public usuarioDTO usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public usuarioDTO usuarioActualizacion {
            get {
                return this.usuarioActualizacionField;
            }
            set {
                this.usuarioActualizacionField = value;
                this.RaisePropertyChanged("usuarioActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public usuarioDTO usuarioCreacion {
            get {
                return this.usuarioCreacionField;
            }
            set {
                this.usuarioCreacionField = value;
                this.RaisePropertyChanged("usuarioCreacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarDireccion", WrapperNamespace="http://usuario.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarDireccionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftWA.Direccion.direccionDTO direccion;
        
        public insertarDireccionRequest() {
        }
        
        public insertarDireccionRequest(SoftWA.Direccion.direccionDTO direccion) {
            this.direccion = direccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarDireccionResponse", WrapperNamespace="http://usuario.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarDireccionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarDireccionResponse() {
        }
        
        public insertarDireccionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarDireccion", WrapperNamespace="http://usuario.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarDireccionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftWA.Direccion.direccionDTO direccion;
        
        public modificarDireccionRequest() {
        }
        
        public modificarDireccionRequest(SoftWA.Direccion.direccionDTO direccion) {
            this.direccion = direccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarDireccionResponse", WrapperNamespace="http://usuario.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarDireccionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarDireccionResponse() {
        }
        
        public modificarDireccionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarDireccion", WrapperNamespace="http://usuario.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarDireccionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftWA.Direccion.direccionDTO direccion;
        
        public eliminarDireccionRequest() {
        }
        
        public eliminarDireccionRequest(SoftWA.Direccion.direccionDTO direccion) {
            this.direccion = direccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarDireccionResponse", WrapperNamespace="http://usuario.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarDireccionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarDireccionResponse() {
        }
        
        public eliminarDireccionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdDireccion", WrapperNamespace="http://usuario.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdDireccionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idDireccion;
        
        public obtenerPorIdDireccionRequest() {
        }
        
        public obtenerPorIdDireccionRequest(int idDireccion) {
            this.idDireccion = idDireccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdDireccionResponse", WrapperNamespace="http://usuario.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdDireccionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftWA.Direccion.direccionDTO @return;
        
        public obtenerPorIdDireccionResponse() {
        }
        
        public obtenerPorIdDireccionResponse(SoftWA.Direccion.direccionDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosDireccion", WrapperNamespace="http://usuario.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosDireccionRequest {
        
        public listarTodosDireccionRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosDireccionResponse", WrapperNamespace="http://usuario.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosDireccionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usuario.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftWA.Direccion.direccionDTO[] @return;
        
        public listarTodosDireccionResponse() {
        }
        
        public listarTodosDireccionResponse(SoftWA.Direccion.direccionDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DireccionChannel : SoftWA.Direccion.Direccion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DireccionClient : System.ServiceModel.ClientBase<SoftWA.Direccion.Direccion>, SoftWA.Direccion.Direccion {
        
        public DireccionClient() {
        }
        
        public DireccionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DireccionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DireccionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DireccionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftWA.Direccion.insertarDireccionResponse SoftWA.Direccion.Direccion.insertarDireccion(SoftWA.Direccion.insertarDireccionRequest request) {
            return base.Channel.insertarDireccion(request);
        }
        
        public int insertarDireccion(SoftWA.Direccion.direccionDTO direccion) {
            SoftWA.Direccion.insertarDireccionRequest inValue = new SoftWA.Direccion.insertarDireccionRequest();
            inValue.direccion = direccion;
            SoftWA.Direccion.insertarDireccionResponse retVal = ((SoftWA.Direccion.Direccion)(this)).insertarDireccion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftWA.Direccion.insertarDireccionResponse> SoftWA.Direccion.Direccion.insertarDireccionAsync(SoftWA.Direccion.insertarDireccionRequest request) {
            return base.Channel.insertarDireccionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftWA.Direccion.insertarDireccionResponse> insertarDireccionAsync(SoftWA.Direccion.direccionDTO direccion) {
            SoftWA.Direccion.insertarDireccionRequest inValue = new SoftWA.Direccion.insertarDireccionRequest();
            inValue.direccion = direccion;
            return ((SoftWA.Direccion.Direccion)(this)).insertarDireccionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftWA.Direccion.modificarDireccionResponse SoftWA.Direccion.Direccion.modificarDireccion(SoftWA.Direccion.modificarDireccionRequest request) {
            return base.Channel.modificarDireccion(request);
        }
        
        public int modificarDireccion(SoftWA.Direccion.direccionDTO direccion) {
            SoftWA.Direccion.modificarDireccionRequest inValue = new SoftWA.Direccion.modificarDireccionRequest();
            inValue.direccion = direccion;
            SoftWA.Direccion.modificarDireccionResponse retVal = ((SoftWA.Direccion.Direccion)(this)).modificarDireccion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftWA.Direccion.modificarDireccionResponse> SoftWA.Direccion.Direccion.modificarDireccionAsync(SoftWA.Direccion.modificarDireccionRequest request) {
            return base.Channel.modificarDireccionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftWA.Direccion.modificarDireccionResponse> modificarDireccionAsync(SoftWA.Direccion.direccionDTO direccion) {
            SoftWA.Direccion.modificarDireccionRequest inValue = new SoftWA.Direccion.modificarDireccionRequest();
            inValue.direccion = direccion;
            return ((SoftWA.Direccion.Direccion)(this)).modificarDireccionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftWA.Direccion.eliminarDireccionResponse SoftWA.Direccion.Direccion.eliminarDireccion(SoftWA.Direccion.eliminarDireccionRequest request) {
            return base.Channel.eliminarDireccion(request);
        }
        
        public int eliminarDireccion(SoftWA.Direccion.direccionDTO direccion) {
            SoftWA.Direccion.eliminarDireccionRequest inValue = new SoftWA.Direccion.eliminarDireccionRequest();
            inValue.direccion = direccion;
            SoftWA.Direccion.eliminarDireccionResponse retVal = ((SoftWA.Direccion.Direccion)(this)).eliminarDireccion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftWA.Direccion.eliminarDireccionResponse> SoftWA.Direccion.Direccion.eliminarDireccionAsync(SoftWA.Direccion.eliminarDireccionRequest request) {
            return base.Channel.eliminarDireccionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftWA.Direccion.eliminarDireccionResponse> eliminarDireccionAsync(SoftWA.Direccion.direccionDTO direccion) {
            SoftWA.Direccion.eliminarDireccionRequest inValue = new SoftWA.Direccion.eliminarDireccionRequest();
            inValue.direccion = direccion;
            return ((SoftWA.Direccion.Direccion)(this)).eliminarDireccionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftWA.Direccion.obtenerPorIdDireccionResponse SoftWA.Direccion.Direccion.obtenerPorIdDireccion(SoftWA.Direccion.obtenerPorIdDireccionRequest request) {
            return base.Channel.obtenerPorIdDireccion(request);
        }
        
        public SoftWA.Direccion.direccionDTO obtenerPorIdDireccion(int idDireccion) {
            SoftWA.Direccion.obtenerPorIdDireccionRequest inValue = new SoftWA.Direccion.obtenerPorIdDireccionRequest();
            inValue.idDireccion = idDireccion;
            SoftWA.Direccion.obtenerPorIdDireccionResponse retVal = ((SoftWA.Direccion.Direccion)(this)).obtenerPorIdDireccion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftWA.Direccion.obtenerPorIdDireccionResponse> SoftWA.Direccion.Direccion.obtenerPorIdDireccionAsync(SoftWA.Direccion.obtenerPorIdDireccionRequest request) {
            return base.Channel.obtenerPorIdDireccionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftWA.Direccion.obtenerPorIdDireccionResponse> obtenerPorIdDireccionAsync(int idDireccion) {
            SoftWA.Direccion.obtenerPorIdDireccionRequest inValue = new SoftWA.Direccion.obtenerPorIdDireccionRequest();
            inValue.idDireccion = idDireccion;
            return ((SoftWA.Direccion.Direccion)(this)).obtenerPorIdDireccionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftWA.Direccion.listarTodosDireccionResponse SoftWA.Direccion.Direccion.listarTodosDireccion(SoftWA.Direccion.listarTodosDireccionRequest request) {
            return base.Channel.listarTodosDireccion(request);
        }
        
        public SoftWA.Direccion.direccionDTO[] listarTodosDireccion() {
            SoftWA.Direccion.listarTodosDireccionRequest inValue = new SoftWA.Direccion.listarTodosDireccionRequest();
            SoftWA.Direccion.listarTodosDireccionResponse retVal = ((SoftWA.Direccion.Direccion)(this)).listarTodosDireccion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftWA.Direccion.listarTodosDireccionResponse> SoftWA.Direccion.Direccion.listarTodosDireccionAsync(SoftWA.Direccion.listarTodosDireccionRequest request) {
            return base.Channel.listarTodosDireccionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftWA.Direccion.listarTodosDireccionResponse> listarTodosDireccionAsync() {
            SoftWA.Direccion.listarTodosDireccionRequest inValue = new SoftWA.Direccion.listarTodosDireccionRequest();
            return ((SoftWA.Direccion.Direccion)(this)).listarTodosDireccionAsync(inValue);
        }
    }
}
