//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftWA.ItemCarrito {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/", ConfigurationName="ItemCarrito.ItemCarrito")]
    public interface ItemCarrito {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://pedido.services.softprog.pucp.edu.pe/ItemCarrito/insertarItemCarritoReques" +
            "t", ReplyAction="http://pedido.services.softprog.pucp.edu.pe/ItemCarrito/insertarItemCarritoRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftWA.ItemCarrito.insertarItemCarritoResponse insertarItemCarrito(SoftWA.ItemCarrito.insertarItemCarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pedido.services.softprog.pucp.edu.pe/ItemCarrito/insertarItemCarritoReques" +
            "t", ReplyAction="http://pedido.services.softprog.pucp.edu.pe/ItemCarrito/insertarItemCarritoRespon" +
            "se")]
        System.Threading.Tasks.Task<SoftWA.ItemCarrito.insertarItemCarritoResponse> insertarItemCarritoAsync(SoftWA.ItemCarrito.insertarItemCarritoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://pedido.services.softprog.pucp.edu.pe/ItemCarrito/listarTodosItemCarritoReq" +
            "uest", ReplyAction="http://pedido.services.softprog.pucp.edu.pe/ItemCarrito/listarTodosItemCarritoRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftWA.ItemCarrito.listarTodosItemCarritoResponse listarTodosItemCarrito(SoftWA.ItemCarrito.listarTodosItemCarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pedido.services.softprog.pucp.edu.pe/ItemCarrito/listarTodosItemCarritoReq" +
            "uest", ReplyAction="http://pedido.services.softprog.pucp.edu.pe/ItemCarrito/listarTodosItemCarritoRes" +
            "ponse")]
        System.Threading.Tasks.Task<SoftWA.ItemCarrito.listarTodosItemCarritoResponse> listarTodosItemCarritoAsync(SoftWA.ItemCarrito.listarTodosItemCarritoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://pedido.services.softprog.pucp.edu.pe/ItemCarrito/eliminarItemCarritoReques" +
            "t", ReplyAction="http://pedido.services.softprog.pucp.edu.pe/ItemCarrito/eliminarItemCarritoRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftWA.ItemCarrito.eliminarItemCarritoResponse eliminarItemCarrito(SoftWA.ItemCarrito.eliminarItemCarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pedido.services.softprog.pucp.edu.pe/ItemCarrito/eliminarItemCarritoReques" +
            "t", ReplyAction="http://pedido.services.softprog.pucp.edu.pe/ItemCarrito/eliminarItemCarritoRespon" +
            "se")]
        System.Threading.Tasks.Task<SoftWA.ItemCarrito.eliminarItemCarritoResponse> eliminarItemCarritoAsync(SoftWA.ItemCarrito.eliminarItemCarritoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://pedido.services.softprog.pucp.edu.pe/ItemCarrito/modificarItemCarritoReque" +
            "st", ReplyAction="http://pedido.services.softprog.pucp.edu.pe/ItemCarrito/modificarItemCarritoRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftWA.ItemCarrito.modificarItemCarritoResponse modificarItemCarrito(SoftWA.ItemCarrito.modificarItemCarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pedido.services.softprog.pucp.edu.pe/ItemCarrito/modificarItemCarritoReque" +
            "st", ReplyAction="http://pedido.services.softprog.pucp.edu.pe/ItemCarrito/modificarItemCarritoRespo" +
            "nse")]
        System.Threading.Tasks.Task<SoftWA.ItemCarrito.modificarItemCarritoResponse> modificarItemCarritoAsync(SoftWA.ItemCarrito.modificarItemCarritoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://pedido.services.softprog.pucp.edu.pe/ItemCarrito/obtenerPorIdItemCarritoRe" +
            "quest", ReplyAction="http://pedido.services.softprog.pucp.edu.pe/ItemCarrito/obtenerPorIdItemCarritoRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftWA.ItemCarrito.obtenerPorIdItemCarritoResponse obtenerPorIdItemCarrito(SoftWA.ItemCarrito.obtenerPorIdItemCarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pedido.services.softprog.pucp.edu.pe/ItemCarrito/obtenerPorIdItemCarritoRe" +
            "quest", ReplyAction="http://pedido.services.softprog.pucp.edu.pe/ItemCarrito/obtenerPorIdItemCarritoRe" +
            "sponse")]
        System.Threading.Tasks.Task<SoftWA.ItemCarrito.obtenerPorIdItemCarritoResponse> obtenerPorIdItemCarritoAsync(SoftWA.ItemCarrito.obtenerPorIdItemCarritoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/")]
    public partial class itemCarritoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private int cantidadField;
        
        private carritoDTO carritoField;
        
        private localDateTime fechaActualizacionField;
        
        private localDateTime fechaCreacionField;
        
        private int idItemCarritoField;
        
        private productoDTO productoField;
        
        private double subtotalField;
        
        private usuarioDTO usuarioActualizacionField;
        
        private usuarioDTO usuarioCreacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public carritoDTO carrito {
            get {
                return this.carritoField;
            }
            set {
                this.carritoField = value;
                this.RaisePropertyChanged("carrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public localDateTime fechaActualizacion {
            get {
                return this.fechaActualizacionField;
            }
            set {
                this.fechaActualizacionField = value;
                this.RaisePropertyChanged("fechaActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public localDateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idItemCarrito {
            get {
                return this.idItemCarritoField;
            }
            set {
                this.idItemCarritoField = value;
                this.RaisePropertyChanged("idItemCarrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public productoDTO producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double subtotal {
            get {
                return this.subtotalField;
            }
            set {
                this.subtotalField = value;
                this.RaisePropertyChanged("subtotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public usuarioDTO usuarioActualizacion {
            get {
                return this.usuarioActualizacionField;
            }
            set {
                this.usuarioActualizacionField = value;
                this.RaisePropertyChanged("usuarioActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public usuarioDTO usuarioCreacion {
            get {
                return this.usuarioCreacionField;
            }
            set {
                this.usuarioCreacionField = value;
                this.RaisePropertyChanged("usuarioCreacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/")]
    public partial class carritoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private localDateTime fechaActualizacionField;
        
        private localDateTime fechaCreacionField;
        
        private int idCarritoField;
        
        private itemCarritoDTO[] itemsField;
        
        private personaDTO personaField;
        
        private double totalField;
        
        private usuarioDTO usuarioActualizacionField;
        
        private usuarioDTO usuarioCreacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public localDateTime fechaActualizacion {
            get {
                return this.fechaActualizacionField;
            }
            set {
                this.fechaActualizacionField = value;
                this.RaisePropertyChanged("fechaActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public localDateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idCarrito {
            get {
                return this.idCarritoField;
            }
            set {
                this.idCarritoField = value;
                this.RaisePropertyChanged("idCarrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("items", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public itemCarritoDTO[] items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public personaDTO persona {
            get {
                return this.personaField;
            }
            set {
                this.personaField = value;
                this.RaisePropertyChanged("persona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public usuarioDTO usuarioActualizacion {
            get {
                return this.usuarioActualizacionField;
            }
            set {
                this.usuarioActualizacionField = value;
                this.RaisePropertyChanged("usuarioActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public usuarioDTO usuarioCreacion {
            get {
                return this.usuarioCreacionField;
            }
            set {
                this.usuarioCreacionField = value;
                this.RaisePropertyChanged("usuarioCreacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/")]
    public partial class localDateTime : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/")]
    public partial class precioPresentacionDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private int cantidadField;
        
        private localDateTime fechaActualizacionField;
        
        private localDateTime fechaCreacionField;
        
        private int idPrecioPresentacionField;
        
        private double precioField;
        
        private productoDTO productoField;
        
        private tipoMedida tipoMedidaField;
        
        private bool tipoMedidaFieldSpecified;
        
        private usuarioDTO usuarioActualizacionField;
        
        private usuarioDTO usuarioCreacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public localDateTime fechaActualizacion {
            get {
                return this.fechaActualizacionField;
            }
            set {
                this.fechaActualizacionField = value;
                this.RaisePropertyChanged("fechaActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public localDateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idPrecioPresentacion {
            get {
                return this.idPrecioPresentacionField;
            }
            set {
                this.idPrecioPresentacionField = value;
                this.RaisePropertyChanged("idPrecioPresentacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public productoDTO producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public tipoMedida tipoMedida {
            get {
                return this.tipoMedidaField;
            }
            set {
                this.tipoMedidaField = value;
                this.RaisePropertyChanged("tipoMedida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoMedidaSpecified {
            get {
                return this.tipoMedidaFieldSpecified;
            }
            set {
                this.tipoMedidaFieldSpecified = value;
                this.RaisePropertyChanged("tipoMedidaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public usuarioDTO usuarioActualizacion {
            get {
                return this.usuarioActualizacionField;
            }
            set {
                this.usuarioActualizacionField = value;
                this.RaisePropertyChanged("usuarioActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public usuarioDTO usuarioCreacion {
            get {
                return this.usuarioCreacionField;
            }
            set {
                this.usuarioCreacionField = value;
                this.RaisePropertyChanged("usuarioCreacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/")]
    public partial class productoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private string categoriaField;
        
        private string descripcionField;
        
        private localDateTime fechaActualizacionField;
        
        private localDateTime fechaCreacionField;
        
        private int idProductoField;
        
        private string nombreField;
        
        private double precioField;
        
        private precioPresentacionDTO[] preciosPorPresentacionesField;
        
        private int stockField;
        
        private usuarioDTO usuarioActualizacionField;
        
        private usuarioDTO usuarioCreacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public localDateTime fechaActualizacion {
            get {
                return this.fechaActualizacionField;
            }
            set {
                this.fechaActualizacionField = value;
                this.RaisePropertyChanged("fechaActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public localDateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
                this.RaisePropertyChanged("idProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("preciosPorPresentaciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public precioPresentacionDTO[] preciosPorPresentaciones {
            get {
                return this.preciosPorPresentacionesField;
            }
            set {
                this.preciosPorPresentacionesField = value;
                this.RaisePropertyChanged("preciosPorPresentaciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
                this.RaisePropertyChanged("stock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public usuarioDTO usuarioActualizacion {
            get {
                return this.usuarioActualizacionField;
            }
            set {
                this.usuarioActualizacionField = value;
                this.RaisePropertyChanged("usuarioActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public usuarioDTO usuarioCreacion {
            get {
                return this.usuarioCreacionField;
            }
            set {
                this.usuarioCreacionField = value;
                this.RaisePropertyChanged("usuarioCreacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/")]
    public partial class usuarioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private string contraseñaField;
        
        private string emailField;
        
        private int idField;
        
        private rolDTO rolField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                this.contraseñaField = value;
                this.RaisePropertyChanged("contraseña");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public rolDTO rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
                this.RaisePropertyChanged("rol");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/")]
    public partial class rolDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private int idField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/")]
    public enum tipoMedida {
        
        /// <remarks/>
        DECENA,
        
        /// <remarks/>
        DOCENA,
        
        /// <remarks/>
        CENTENA,
        
        /// <remarks/>
        MILLAR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/")]
    public partial class direccionDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private string aliasField;
        
        private string ciudadField;
        
        private string direccionField;
        
        private localDateTime fechaActualizacionField;
        
        private localDateTime fechaCreacionField;
        
        private int idField;
        
        private personaDTO personaIdField;
        
        private string referenciaField;
        
        private usuarioDTO usuarioActualizacionField;
        
        private usuarioDTO usuarioCreacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
                this.RaisePropertyChanged("alias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ciudad {
            get {
                return this.ciudadField;
            }
            set {
                this.ciudadField = value;
                this.RaisePropertyChanged("ciudad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public localDateTime fechaActualizacion {
            get {
                return this.fechaActualizacionField;
            }
            set {
                this.fechaActualizacionField = value;
                this.RaisePropertyChanged("fechaActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public localDateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public personaDTO personaId {
            get {
                return this.personaIdField;
            }
            set {
                this.personaIdField = value;
                this.RaisePropertyChanged("personaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
                this.RaisePropertyChanged("referencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public usuarioDTO usuarioActualizacion {
            get {
                return this.usuarioActualizacionField;
            }
            set {
                this.usuarioActualizacionField = value;
                this.RaisePropertyChanged("usuarioActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public usuarioDTO usuarioCreacion {
            get {
                return this.usuarioCreacionField;
            }
            set {
                this.usuarioCreacionField = value;
                this.RaisePropertyChanged("usuarioCreacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/")]
    public partial class personaDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private string apellidosField;
        
        private direccionDTO[] direccionesField;
        
        private localDateTime fechaActualizacionField;
        
        private localDateTime fechaCreacionField;
        
        private int idField;
        
        private string nombresField;
        
        private string telefonoField;
        
        private usuarioDTO usuarioField;
        
        private usuarioDTO usuarioActualizacionField;
        
        private usuarioDTO usuarioCreacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("direcciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public direccionDTO[] direcciones {
            get {
                return this.direccionesField;
            }
            set {
                this.direccionesField = value;
                this.RaisePropertyChanged("direcciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public localDateTime fechaActualizacion {
            get {
                return this.fechaActualizacionField;
            }
            set {
                this.fechaActualizacionField = value;
                this.RaisePropertyChanged("fechaActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public localDateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public usuarioDTO usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public usuarioDTO usuarioActualizacion {
            get {
                return this.usuarioActualizacionField;
            }
            set {
                this.usuarioActualizacionField = value;
                this.RaisePropertyChanged("usuarioActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public usuarioDTO usuarioCreacion {
            get {
                return this.usuarioCreacionField;
            }
            set {
                this.usuarioCreacionField = value;
                this.RaisePropertyChanged("usuarioCreacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarItemCarrito", WrapperNamespace="http://pedido.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarItemCarritoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftWA.ItemCarrito.itemCarritoDTO itemCarrito;
        
        public insertarItemCarritoRequest() {
        }
        
        public insertarItemCarritoRequest(SoftWA.ItemCarrito.itemCarritoDTO itemCarrito) {
            this.itemCarrito = itemCarrito;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarItemCarritoResponse", WrapperNamespace="http://pedido.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarItemCarritoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarItemCarritoResponse() {
        }
        
        public insertarItemCarritoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosItemCarrito", WrapperNamespace="http://pedido.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosItemCarritoRequest {
        
        public listarTodosItemCarritoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosItemCarritoResponse", WrapperNamespace="http://pedido.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosItemCarritoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftWA.ItemCarrito.itemCarritoDTO[] @return;
        
        public listarTodosItemCarritoResponse() {
        }
        
        public listarTodosItemCarritoResponse(SoftWA.ItemCarrito.itemCarritoDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarItemCarrito", WrapperNamespace="http://pedido.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarItemCarritoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftWA.ItemCarrito.itemCarritoDTO itemCarrito;
        
        public eliminarItemCarritoRequest() {
        }
        
        public eliminarItemCarritoRequest(SoftWA.ItemCarrito.itemCarritoDTO itemCarrito) {
            this.itemCarrito = itemCarrito;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarItemCarritoResponse", WrapperNamespace="http://pedido.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarItemCarritoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarItemCarritoResponse() {
        }
        
        public eliminarItemCarritoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarItemCarrito", WrapperNamespace="http://pedido.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarItemCarritoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftWA.ItemCarrito.itemCarritoDTO itemCarrito;
        
        public modificarItemCarritoRequest() {
        }
        
        public modificarItemCarritoRequest(SoftWA.ItemCarrito.itemCarritoDTO itemCarrito) {
            this.itemCarrito = itemCarrito;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarItemCarritoResponse", WrapperNamespace="http://pedido.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarItemCarritoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarItemCarritoResponse() {
        }
        
        public modificarItemCarritoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdItemCarrito", WrapperNamespace="http://pedido.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdItemCarritoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idItemCarrito;
        
        public obtenerPorIdItemCarritoRequest() {
        }
        
        public obtenerPorIdItemCarritoRequest(int idItemCarrito) {
            this.idItemCarrito = idItemCarrito;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdItemCarritoResponse", WrapperNamespace="http://pedido.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdItemCarritoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pedido.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftWA.ItemCarrito.itemCarritoDTO @return;
        
        public obtenerPorIdItemCarritoResponse() {
        }
        
        public obtenerPorIdItemCarritoResponse(SoftWA.ItemCarrito.itemCarritoDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ItemCarritoChannel : SoftWA.ItemCarrito.ItemCarrito, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ItemCarritoClient : System.ServiceModel.ClientBase<SoftWA.ItemCarrito.ItemCarrito>, SoftWA.ItemCarrito.ItemCarrito {
        
        public ItemCarritoClient() {
        }
        
        public ItemCarritoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ItemCarritoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItemCarritoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItemCarritoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftWA.ItemCarrito.insertarItemCarritoResponse SoftWA.ItemCarrito.ItemCarrito.insertarItemCarrito(SoftWA.ItemCarrito.insertarItemCarritoRequest request) {
            return base.Channel.insertarItemCarrito(request);
        }
        
        public int insertarItemCarrito(SoftWA.ItemCarrito.itemCarritoDTO itemCarrito) {
            SoftWA.ItemCarrito.insertarItemCarritoRequest inValue = new SoftWA.ItemCarrito.insertarItemCarritoRequest();
            inValue.itemCarrito = itemCarrito;
            SoftWA.ItemCarrito.insertarItemCarritoResponse retVal = ((SoftWA.ItemCarrito.ItemCarrito)(this)).insertarItemCarrito(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftWA.ItemCarrito.insertarItemCarritoResponse> SoftWA.ItemCarrito.ItemCarrito.insertarItemCarritoAsync(SoftWA.ItemCarrito.insertarItemCarritoRequest request) {
            return base.Channel.insertarItemCarritoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftWA.ItemCarrito.insertarItemCarritoResponse> insertarItemCarritoAsync(SoftWA.ItemCarrito.itemCarritoDTO itemCarrito) {
            SoftWA.ItemCarrito.insertarItemCarritoRequest inValue = new SoftWA.ItemCarrito.insertarItemCarritoRequest();
            inValue.itemCarrito = itemCarrito;
            return ((SoftWA.ItemCarrito.ItemCarrito)(this)).insertarItemCarritoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftWA.ItemCarrito.listarTodosItemCarritoResponse SoftWA.ItemCarrito.ItemCarrito.listarTodosItemCarrito(SoftWA.ItemCarrito.listarTodosItemCarritoRequest request) {
            return base.Channel.listarTodosItemCarrito(request);
        }
        
        public SoftWA.ItemCarrito.itemCarritoDTO[] listarTodosItemCarrito() {
            SoftWA.ItemCarrito.listarTodosItemCarritoRequest inValue = new SoftWA.ItemCarrito.listarTodosItemCarritoRequest();
            SoftWA.ItemCarrito.listarTodosItemCarritoResponse retVal = ((SoftWA.ItemCarrito.ItemCarrito)(this)).listarTodosItemCarrito(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftWA.ItemCarrito.listarTodosItemCarritoResponse> SoftWA.ItemCarrito.ItemCarrito.listarTodosItemCarritoAsync(SoftWA.ItemCarrito.listarTodosItemCarritoRequest request) {
            return base.Channel.listarTodosItemCarritoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftWA.ItemCarrito.listarTodosItemCarritoResponse> listarTodosItemCarritoAsync() {
            SoftWA.ItemCarrito.listarTodosItemCarritoRequest inValue = new SoftWA.ItemCarrito.listarTodosItemCarritoRequest();
            return ((SoftWA.ItemCarrito.ItemCarrito)(this)).listarTodosItemCarritoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftWA.ItemCarrito.eliminarItemCarritoResponse SoftWA.ItemCarrito.ItemCarrito.eliminarItemCarrito(SoftWA.ItemCarrito.eliminarItemCarritoRequest request) {
            return base.Channel.eliminarItemCarrito(request);
        }
        
        public int eliminarItemCarrito(SoftWA.ItemCarrito.itemCarritoDTO itemCarrito) {
            SoftWA.ItemCarrito.eliminarItemCarritoRequest inValue = new SoftWA.ItemCarrito.eliminarItemCarritoRequest();
            inValue.itemCarrito = itemCarrito;
            SoftWA.ItemCarrito.eliminarItemCarritoResponse retVal = ((SoftWA.ItemCarrito.ItemCarrito)(this)).eliminarItemCarrito(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftWA.ItemCarrito.eliminarItemCarritoResponse> SoftWA.ItemCarrito.ItemCarrito.eliminarItemCarritoAsync(SoftWA.ItemCarrito.eliminarItemCarritoRequest request) {
            return base.Channel.eliminarItemCarritoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftWA.ItemCarrito.eliminarItemCarritoResponse> eliminarItemCarritoAsync(SoftWA.ItemCarrito.itemCarritoDTO itemCarrito) {
            SoftWA.ItemCarrito.eliminarItemCarritoRequest inValue = new SoftWA.ItemCarrito.eliminarItemCarritoRequest();
            inValue.itemCarrito = itemCarrito;
            return ((SoftWA.ItemCarrito.ItemCarrito)(this)).eliminarItemCarritoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftWA.ItemCarrito.modificarItemCarritoResponse SoftWA.ItemCarrito.ItemCarrito.modificarItemCarrito(SoftWA.ItemCarrito.modificarItemCarritoRequest request) {
            return base.Channel.modificarItemCarrito(request);
        }
        
        public int modificarItemCarrito(SoftWA.ItemCarrito.itemCarritoDTO itemCarrito) {
            SoftWA.ItemCarrito.modificarItemCarritoRequest inValue = new SoftWA.ItemCarrito.modificarItemCarritoRequest();
            inValue.itemCarrito = itemCarrito;
            SoftWA.ItemCarrito.modificarItemCarritoResponse retVal = ((SoftWA.ItemCarrito.ItemCarrito)(this)).modificarItemCarrito(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftWA.ItemCarrito.modificarItemCarritoResponse> SoftWA.ItemCarrito.ItemCarrito.modificarItemCarritoAsync(SoftWA.ItemCarrito.modificarItemCarritoRequest request) {
            return base.Channel.modificarItemCarritoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftWA.ItemCarrito.modificarItemCarritoResponse> modificarItemCarritoAsync(SoftWA.ItemCarrito.itemCarritoDTO itemCarrito) {
            SoftWA.ItemCarrito.modificarItemCarritoRequest inValue = new SoftWA.ItemCarrito.modificarItemCarritoRequest();
            inValue.itemCarrito = itemCarrito;
            return ((SoftWA.ItemCarrito.ItemCarrito)(this)).modificarItemCarritoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftWA.ItemCarrito.obtenerPorIdItemCarritoResponse SoftWA.ItemCarrito.ItemCarrito.obtenerPorIdItemCarrito(SoftWA.ItemCarrito.obtenerPorIdItemCarritoRequest request) {
            return base.Channel.obtenerPorIdItemCarrito(request);
        }
        
        public SoftWA.ItemCarrito.itemCarritoDTO obtenerPorIdItemCarrito(int idItemCarrito) {
            SoftWA.ItemCarrito.obtenerPorIdItemCarritoRequest inValue = new SoftWA.ItemCarrito.obtenerPorIdItemCarritoRequest();
            inValue.idItemCarrito = idItemCarrito;
            SoftWA.ItemCarrito.obtenerPorIdItemCarritoResponse retVal = ((SoftWA.ItemCarrito.ItemCarrito)(this)).obtenerPorIdItemCarrito(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftWA.ItemCarrito.obtenerPorIdItemCarritoResponse> SoftWA.ItemCarrito.ItemCarrito.obtenerPorIdItemCarritoAsync(SoftWA.ItemCarrito.obtenerPorIdItemCarritoRequest request) {
            return base.Channel.obtenerPorIdItemCarritoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftWA.ItemCarrito.obtenerPorIdItemCarritoResponse> obtenerPorIdItemCarritoAsync(int idItemCarrito) {
            SoftWA.ItemCarrito.obtenerPorIdItemCarritoRequest inValue = new SoftWA.ItemCarrito.obtenerPorIdItemCarritoRequest();
            inValue.idItemCarrito = idItemCarrito;
            return ((SoftWA.ItemCarrito.ItemCarrito)(this)).obtenerPorIdItemCarritoAsync(inValue);
        }
    }
}
