//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftWA.Producto {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://producto.services.softprog.pucp.edu.pe/", ConfigurationName="Producto.Productos")]
    public interface Productos {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://producto.services.softprog.pucp.edu.pe/Productos/insertarProductoRequest", ReplyAction="http://producto.services.softprog.pucp.edu.pe/Productos/insertarProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftWA.Producto.insertarProductoResponse insertarProducto(SoftWA.Producto.insertarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://producto.services.softprog.pucp.edu.pe/Productos/insertarProductoRequest", ReplyAction="http://producto.services.softprog.pucp.edu.pe/Productos/insertarProductoResponse")]
        System.Threading.Tasks.Task<SoftWA.Producto.insertarProductoResponse> insertarProductoAsync(SoftWA.Producto.insertarProductoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://producto.services.softprog.pucp.edu.pe/Productos/eliminarProductoRequest", ReplyAction="http://producto.services.softprog.pucp.edu.pe/Productos/eliminarProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftWA.Producto.eliminarProductoResponse eliminarProducto(SoftWA.Producto.eliminarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://producto.services.softprog.pucp.edu.pe/Productos/eliminarProductoRequest", ReplyAction="http://producto.services.softprog.pucp.edu.pe/Productos/eliminarProductoResponse")]
        System.Threading.Tasks.Task<SoftWA.Producto.eliminarProductoResponse> eliminarProductoAsync(SoftWA.Producto.eliminarProductoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://producto.services.softprog.pucp.edu.pe/Productos/modificarProductoRequest", ReplyAction="http://producto.services.softprog.pucp.edu.pe/Productos/modificarProductoResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftWA.Producto.modificarProductoResponse modificarProducto(SoftWA.Producto.modificarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://producto.services.softprog.pucp.edu.pe/Productos/modificarProductoRequest", ReplyAction="http://producto.services.softprog.pucp.edu.pe/Productos/modificarProductoResponse" +
            "")]
        System.Threading.Tasks.Task<SoftWA.Producto.modificarProductoResponse> modificarProductoAsync(SoftWA.Producto.modificarProductoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://producto.services.softprog.pucp.edu.pe/Productos/obtenerPorIdProductoReque" +
            "st", ReplyAction="http://producto.services.softprog.pucp.edu.pe/Productos/obtenerPorIdProductoRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftWA.Producto.obtenerPorIdProductoResponse obtenerPorIdProducto(SoftWA.Producto.obtenerPorIdProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://producto.services.softprog.pucp.edu.pe/Productos/obtenerPorIdProductoReque" +
            "st", ReplyAction="http://producto.services.softprog.pucp.edu.pe/Productos/obtenerPorIdProductoRespo" +
            "nse")]
        System.Threading.Tasks.Task<SoftWA.Producto.obtenerPorIdProductoResponse> obtenerPorIdProductoAsync(SoftWA.Producto.obtenerPorIdProductoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://producto.services.softprog.pucp.edu.pe/Productos/listarTodosProductoReques" +
            "t", ReplyAction="http://producto.services.softprog.pucp.edu.pe/Productos/listarTodosProductoRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftWA.Producto.listarTodosProductoResponse listarTodosProducto(SoftWA.Producto.listarTodosProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://producto.services.softprog.pucp.edu.pe/Productos/listarTodosProductoReques" +
            "t", ReplyAction="http://producto.services.softprog.pucp.edu.pe/Productos/listarTodosProductoRespon" +
            "se")]
        System.Threading.Tasks.Task<SoftWA.Producto.listarTodosProductoResponse> listarTodosProductoAsync(SoftWA.Producto.listarTodosProductoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://producto.services.softprog.pucp.edu.pe/")]
    public partial class usuarioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private string contraseñaField;
        
        private string emailField;
        
        private int idField;
        
        private rolDTO rolField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                this.contraseñaField = value;
                this.RaisePropertyChanged("contraseña");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public rolDTO rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
                this.RaisePropertyChanged("rol");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://producto.services.softprog.pucp.edu.pe/")]
    public partial class rolDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private int idField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://producto.services.softprog.pucp.edu.pe/")]
    public partial class precioPresentacionDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private int cantidadField;
        
        private localDateTime fechaActualizacionField;
        
        private localDateTime fechaCreacionField;
        
        private int idPrecioPresentacionField;
        
        private double precioField;
        
        private productoDTO productoField;
        
        private tipoMedida tipoMedidaField;
        
        private bool tipoMedidaFieldSpecified;
        
        private usuarioDTO usuarioActualizacionField;
        
        private usuarioDTO usuarioCreacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public localDateTime fechaActualizacion {
            get {
                return this.fechaActualizacionField;
            }
            set {
                this.fechaActualizacionField = value;
                this.RaisePropertyChanged("fechaActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public localDateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idPrecioPresentacion {
            get {
                return this.idPrecioPresentacionField;
            }
            set {
                this.idPrecioPresentacionField = value;
                this.RaisePropertyChanged("idPrecioPresentacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public productoDTO producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public tipoMedida tipoMedida {
            get {
                return this.tipoMedidaField;
            }
            set {
                this.tipoMedidaField = value;
                this.RaisePropertyChanged("tipoMedida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoMedidaSpecified {
            get {
                return this.tipoMedidaFieldSpecified;
            }
            set {
                this.tipoMedidaFieldSpecified = value;
                this.RaisePropertyChanged("tipoMedidaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public usuarioDTO usuarioActualizacion {
            get {
                return this.usuarioActualizacionField;
            }
            set {
                this.usuarioActualizacionField = value;
                this.RaisePropertyChanged("usuarioActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public usuarioDTO usuarioCreacion {
            get {
                return this.usuarioCreacionField;
            }
            set {
                this.usuarioCreacionField = value;
                this.RaisePropertyChanged("usuarioCreacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://producto.services.softprog.pucp.edu.pe/")]
    public partial class localDateTime : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://producto.services.softprog.pucp.edu.pe/")]
    public partial class productoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private string categoriaField;
        
        private string descripcionField;
        
        private localDateTime fechaActualizacionField;
        
        private localDateTime fechaCreacionField;
        
        private int idProductoField;
        
        private string nombreField;
        
        private double precioField;
        
        private precioPresentacionDTO[] preciosPorPresentacionesField;
        
        private int stockField;
        
        private usuarioDTO usuarioActualizacionField;
        
        private usuarioDTO usuarioCreacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public localDateTime fechaActualizacion {
            get {
                return this.fechaActualizacionField;
            }
            set {
                this.fechaActualizacionField = value;
                this.RaisePropertyChanged("fechaActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public localDateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
                this.RaisePropertyChanged("idProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("preciosPorPresentaciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public precioPresentacionDTO[] preciosPorPresentaciones {
            get {
                return this.preciosPorPresentacionesField;
            }
            set {
                this.preciosPorPresentacionesField = value;
                this.RaisePropertyChanged("preciosPorPresentaciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
                this.RaisePropertyChanged("stock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public usuarioDTO usuarioActualizacion {
            get {
                return this.usuarioActualizacionField;
            }
            set {
                this.usuarioActualizacionField = value;
                this.RaisePropertyChanged("usuarioActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public usuarioDTO usuarioCreacion {
            get {
                return this.usuarioCreacionField;
            }
            set {
                this.usuarioCreacionField = value;
                this.RaisePropertyChanged("usuarioCreacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://producto.services.softprog.pucp.edu.pe/")]
    public enum tipoMedida {
        
        /// <remarks/>
        DECENA,
        
        /// <remarks/>
        DOCENA,
        
        /// <remarks/>
        CENTENA,
        
        /// <remarks/>
        MILLAR,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarProducto", WrapperNamespace="http://producto.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://producto.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://producto.services.softprog.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://producto.services.softprog.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double precio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://producto.services.softprog.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int stock;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://producto.services.softprog.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string categoria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://producto.services.softprog.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftWA.Producto.usuarioDTO usuarioCreacion;
        
        public insertarProductoRequest() {
        }
        
        public insertarProductoRequest(string nombre, string descripcion, double precio, int stock, string categoria, SoftWA.Producto.usuarioDTO usuarioCreacion) {
            this.nombre = nombre;
            this.descripcion = descripcion;
            this.precio = precio;
            this.stock = stock;
            this.categoria = categoria;
            this.usuarioCreacion = usuarioCreacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarProductoResponse", WrapperNamespace="http://producto.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://producto.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarProductoResponse() {
        }
        
        public insertarProductoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarProducto", WrapperNamespace="http://producto.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://producto.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftWA.Producto.productoDTO producto;
        
        public eliminarProductoRequest() {
        }
        
        public eliminarProductoRequest(SoftWA.Producto.productoDTO producto) {
            this.producto = producto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarProductoResponse", WrapperNamespace="http://producto.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://producto.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarProductoResponse() {
        }
        
        public eliminarProductoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarProducto", WrapperNamespace="http://producto.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://producto.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int productoId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://producto.services.softprog.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://producto.services.softprog.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://producto.services.softprog.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double precio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://producto.services.softprog.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int stock;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://producto.services.softprog.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string categoria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://producto.services.softprog.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftWA.Producto.usuarioDTO usuarioActualizacion;
        
        public modificarProductoRequest() {
        }
        
        public modificarProductoRequest(int productoId, string nombre, string descripcion, double precio, int stock, string categoria, SoftWA.Producto.usuarioDTO usuarioActualizacion) {
            this.productoId = productoId;
            this.nombre = nombre;
            this.descripcion = descripcion;
            this.precio = precio;
            this.stock = stock;
            this.categoria = categoria;
            this.usuarioActualizacion = usuarioActualizacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarProductoResponse", WrapperNamespace="http://producto.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://producto.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarProductoResponse() {
        }
        
        public modificarProductoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdProducto", WrapperNamespace="http://producto.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://producto.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int productoId;
        
        public obtenerPorIdProductoRequest() {
        }
        
        public obtenerPorIdProductoRequest(int productoId) {
            this.productoId = productoId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdProductoResponse", WrapperNamespace="http://producto.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://producto.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftWA.Producto.productoDTO @return;
        
        public obtenerPorIdProductoResponse() {
        }
        
        public obtenerPorIdProductoResponse(SoftWA.Producto.productoDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosProducto", WrapperNamespace="http://producto.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosProductoRequest {
        
        public listarTodosProductoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosProductoResponse", WrapperNamespace="http://producto.services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://producto.services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftWA.Producto.productoDTO[] @return;
        
        public listarTodosProductoResponse() {
        }
        
        public listarTodosProductoResponse(SoftWA.Producto.productoDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductosChannel : SoftWA.Producto.Productos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductosClient : System.ServiceModel.ClientBase<SoftWA.Producto.Productos>, SoftWA.Producto.Productos {
        
        public ProductosClient() {
        }
        
        public ProductosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftWA.Producto.insertarProductoResponse SoftWA.Producto.Productos.insertarProducto(SoftWA.Producto.insertarProductoRequest request) {
            return base.Channel.insertarProducto(request);
        }
        
        public int insertarProducto(string nombre, string descripcion, double precio, int stock, string categoria, SoftWA.Producto.usuarioDTO usuarioCreacion) {
            SoftWA.Producto.insertarProductoRequest inValue = new SoftWA.Producto.insertarProductoRequest();
            inValue.nombre = nombre;
            inValue.descripcion = descripcion;
            inValue.precio = precio;
            inValue.stock = stock;
            inValue.categoria = categoria;
            inValue.usuarioCreacion = usuarioCreacion;
            SoftWA.Producto.insertarProductoResponse retVal = ((SoftWA.Producto.Productos)(this)).insertarProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftWA.Producto.insertarProductoResponse> SoftWA.Producto.Productos.insertarProductoAsync(SoftWA.Producto.insertarProductoRequest request) {
            return base.Channel.insertarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftWA.Producto.insertarProductoResponse> insertarProductoAsync(string nombre, string descripcion, double precio, int stock, string categoria, SoftWA.Producto.usuarioDTO usuarioCreacion) {
            SoftWA.Producto.insertarProductoRequest inValue = new SoftWA.Producto.insertarProductoRequest();
            inValue.nombre = nombre;
            inValue.descripcion = descripcion;
            inValue.precio = precio;
            inValue.stock = stock;
            inValue.categoria = categoria;
            inValue.usuarioCreacion = usuarioCreacion;
            return ((SoftWA.Producto.Productos)(this)).insertarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftWA.Producto.eliminarProductoResponse SoftWA.Producto.Productos.eliminarProducto(SoftWA.Producto.eliminarProductoRequest request) {
            return base.Channel.eliminarProducto(request);
        }
        
        public int eliminarProducto(SoftWA.Producto.productoDTO producto) {
            SoftWA.Producto.eliminarProductoRequest inValue = new SoftWA.Producto.eliminarProductoRequest();
            inValue.producto = producto;
            SoftWA.Producto.eliminarProductoResponse retVal = ((SoftWA.Producto.Productos)(this)).eliminarProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftWA.Producto.eliminarProductoResponse> SoftWA.Producto.Productos.eliminarProductoAsync(SoftWA.Producto.eliminarProductoRequest request) {
            return base.Channel.eliminarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftWA.Producto.eliminarProductoResponse> eliminarProductoAsync(SoftWA.Producto.productoDTO producto) {
            SoftWA.Producto.eliminarProductoRequest inValue = new SoftWA.Producto.eliminarProductoRequest();
            inValue.producto = producto;
            return ((SoftWA.Producto.Productos)(this)).eliminarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftWA.Producto.modificarProductoResponse SoftWA.Producto.Productos.modificarProducto(SoftWA.Producto.modificarProductoRequest request) {
            return base.Channel.modificarProducto(request);
        }
        
        public int modificarProducto(int productoId, string nombre, string descripcion, double precio, int stock, string categoria, SoftWA.Producto.usuarioDTO usuarioActualizacion) {
            SoftWA.Producto.modificarProductoRequest inValue = new SoftWA.Producto.modificarProductoRequest();
            inValue.productoId = productoId;
            inValue.nombre = nombre;
            inValue.descripcion = descripcion;
            inValue.precio = precio;
            inValue.stock = stock;
            inValue.categoria = categoria;
            inValue.usuarioActualizacion = usuarioActualizacion;
            SoftWA.Producto.modificarProductoResponse retVal = ((SoftWA.Producto.Productos)(this)).modificarProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftWA.Producto.modificarProductoResponse> SoftWA.Producto.Productos.modificarProductoAsync(SoftWA.Producto.modificarProductoRequest request) {
            return base.Channel.modificarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftWA.Producto.modificarProductoResponse> modificarProductoAsync(int productoId, string nombre, string descripcion, double precio, int stock, string categoria, SoftWA.Producto.usuarioDTO usuarioActualizacion) {
            SoftWA.Producto.modificarProductoRequest inValue = new SoftWA.Producto.modificarProductoRequest();
            inValue.productoId = productoId;
            inValue.nombre = nombre;
            inValue.descripcion = descripcion;
            inValue.precio = precio;
            inValue.stock = stock;
            inValue.categoria = categoria;
            inValue.usuarioActualizacion = usuarioActualizacion;
            return ((SoftWA.Producto.Productos)(this)).modificarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftWA.Producto.obtenerPorIdProductoResponse SoftWA.Producto.Productos.obtenerPorIdProducto(SoftWA.Producto.obtenerPorIdProductoRequest request) {
            return base.Channel.obtenerPorIdProducto(request);
        }
        
        public SoftWA.Producto.productoDTO obtenerPorIdProducto(int productoId) {
            SoftWA.Producto.obtenerPorIdProductoRequest inValue = new SoftWA.Producto.obtenerPorIdProductoRequest();
            inValue.productoId = productoId;
            SoftWA.Producto.obtenerPorIdProductoResponse retVal = ((SoftWA.Producto.Productos)(this)).obtenerPorIdProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftWA.Producto.obtenerPorIdProductoResponse> SoftWA.Producto.Productos.obtenerPorIdProductoAsync(SoftWA.Producto.obtenerPorIdProductoRequest request) {
            return base.Channel.obtenerPorIdProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftWA.Producto.obtenerPorIdProductoResponse> obtenerPorIdProductoAsync(int productoId) {
            SoftWA.Producto.obtenerPorIdProductoRequest inValue = new SoftWA.Producto.obtenerPorIdProductoRequest();
            inValue.productoId = productoId;
            return ((SoftWA.Producto.Productos)(this)).obtenerPorIdProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftWA.Producto.listarTodosProductoResponse SoftWA.Producto.Productos.listarTodosProducto(SoftWA.Producto.listarTodosProductoRequest request) {
            return base.Channel.listarTodosProducto(request);
        }
        
        public SoftWA.Producto.productoDTO[] listarTodosProducto() {
            SoftWA.Producto.listarTodosProductoRequest inValue = new SoftWA.Producto.listarTodosProductoRequest();
            SoftWA.Producto.listarTodosProductoResponse retVal = ((SoftWA.Producto.Productos)(this)).listarTodosProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftWA.Producto.listarTodosProductoResponse> SoftWA.Producto.Productos.listarTodosProductoAsync(SoftWA.Producto.listarTodosProductoRequest request) {
            return base.Channel.listarTodosProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftWA.Producto.listarTodosProductoResponse> listarTodosProductoAsync() {
            SoftWA.Producto.listarTodosProductoRequest inValue = new SoftWA.Producto.listarTodosProductoRequest();
            return ((SoftWA.Producto.Productos)(this)).listarTodosProductoAsync(inValue);
        }
    }
}
